= Blaze-Persistence 1.2.1 and 1.3.0-Alpha1 Release
Christian Beikov
2018-07-05 0
:description: Blaze-Persistence version 1.2.1 and 1.3.0-Alpha1 were just released
:page: news
:icon: christian_head.png
:jbake-tags: announcement,release
:jbake-type: post
:jbake-status: published
:linkattrs:

Here comes version 1.2.1 containing a lot of fixes and 1.3.0-Alpha1 containing new API methods that allow to make use of Hibernate Envers entities with Blaze-Persistence!

Thanks for all the testing and issue reports to Giovanni Lovato who helped a lot with getting Blaze-Persistence to work properly with Hibernate Envers!
A big thank you also goes out to Jan-Willem Gmelig Meyling who worked on the support for natural ids and a few other issues!
When he finishes working on a the join avoidance optimization for natural ids in Hibernate we are going+++<!-- PREVIEW-SUFFIX --><!-- </p></div> --><!-- PREVIEW-END -->+++
to add support for the optimization as well so you can enjoy better performance out of the box when updating Hibernate.

Other than that, we only worked on bug fixes. You can find a list of the fixed issues on https://github.com/Blazebit/blaze-persistence/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.2.1[GitHub, window="_blank"].

The next release will be 1.3.0 to be expected by the end of July. We currently do not plan to do any more 1.2 releases unless something critical comes up.
Since 1.3.0-Alpha1 essentially is 1.2.1 with a few additional features, it is safe to update, so please give us feedback on 1.3.0-Alpha1 if you can!