== Architecture

=== Interfaces

==== Basic functionality

{projectname} has a builder API for building JPQL queries in a comfortable fashion.

The most important interfaces that a user should be concerned with are

* `com.blazebit.persistence.CriteriaBuilder`
* `com.blazebit.persistence.PaginatedCriteriaBuilder`

The functionality of the query builders a separated into base interfaces to avoid duplication where possible. All functionality for the `WHERE`-clause for example can be found in `com.blazebit.persistence.BaseWhereBuilder`.
Analogous to that, there also exist interfaces for other clauses.

Unless some advanced features(e.g. CTEs) are used, every query builder has the possibility to render a JPQL query string and retrieve an executable JPA query object. In case of advanced features the query string that is returned might contain syntax elements which are not supported by JPQL. Some features like CTEs simply can not be modeled with JPQL, therefore a syntax similar to SQL was used to visualize the query model.

==== DML support

If a user uses {projectname} for data manipulation too, then the following interfaces are unavoidable to know

* `com.blazebit.persistence.InsertCriteriaBuilder`
* `com.blazebit.persistence.UpdateCriteriaBuilder`
* `com.blazebit.persistence.DeleteCriteriaBuilder`

Every interface has a dual partner interface prefixed with `Returning` that is relevant for data manipulation queries that return results. 

NOTE: The `Returning` interfaces are only relevant when using CTEs (Common Table Expressions)

==== CTE support

CTE builders are split into two families of interface groups. One group is concerned with CTEs that do select queries, the other with DML queries.

Select CTE queries can either be recursive or non-recursive. Recursive CTEs always have a base part and a recursive part which is explicitly modeled in the API. One starts with a `com.blazebit.persistence.SelectRecursiveCTECriteriaBuilder` for defining the base part and then unions the recursive part of the query in  a `com.blazebit.persistence.SelectCTECriteriaBuilder`. The non-recursive builder is very similar but does not have an explicit notion of a base or recursive part. Although it supports set operations, we do not recommend building recursive queries with the non-recursive builder especially because it's not portable and less readable.

==== Set operations support

Every query builder has support for set operations as defined by the interface `com.blazebit.persistence.SetOperationBuilder`. One can start a nested group of query builders concatenated with set operations. This group has to be ended and concatenated with another query build or another nested group.

// TODO: describe parser architecture(pipeline incl. caching) and AST model