== Join clause

JPQL offers support for `CROSS`, `INNER`, `LEFT` and `RIGHT JOIN` which are all well supported by {projectname}. In contrast to JPQL, {projectname} also has a notion of implicit/default and explicit joins which makes it very convenient to write queries as can be seen a few sections later.

NOTE: `RIGHT JOIN`s aren't well defined by JPA so we recommend not using them at all.

=== Implicit joins

An implicit or default join is a special join that can be referred to by an absolute path from a root entity to an association or also by alias if an explicit alias has been defined.

The following query builder will create an implicit join for `kittens` when visiting the select clause and reuse that implicit join in the where clause because of the use of an absolute path.
[source,java]
----
CriteriaBuilder<Integer> cb = cbf.create(em, Integer.class)
 .from(Cat.class)
 .select("kittens.age")
 .where("kittens.age").gt(1);
----

This will result in the following JPQL query
[source,sql]
----
SELECT kittens_1.age FROM Cat cat LEFT JOIN cat.kittens kittens_1 WHERE kittens_1.age > 1
----



TODO: Mention the model awareness +
TODO: Mention implicit aliases shouldn't be use, instead the full path or an alias should be used +

=== Explicit joins

TODO: Mention that array expressions create explicit joins with a specific structure.

==== Default joins

==== Aliased joins

==== Fetched joins

=== On clause

TODO: Mention that it is commonly used by array expressions +
TODO: Warn that on clauses are no supported by JPA 2.0 +
TODO: Also refer to the predicate building section which should explain the basics +