== DML statements

Next to the support for `SELECT` statements, {projectname} also has support for

* `UPDATE`
* `DELETE`
* `INSERT ... SELECT`

The construction of query builders for such statements works through the link:{core_doc}/persistence/CriteriaBuilderFactory.html[`CriteriaBuilderFactory`] API.

=== DELETE statement

The `DELETE` statement deletes entities that satisfy the `WHERE` clause of the statement.
A delete builder can be created via link:{core_doc}/persistence/CriteriaBuilderFactory.html#delete(javax.persistence.EntityManager,%20java.lang.Class,%20java.lang.String)[`CriteriaBuilderFactory.delete()`].

[source,java]
----
DeleteCriteriaBuilder<Cat> cb = cbf.delete(em, Cat.class, "cat")
    .where("cat.name").isNull();
----

[source,sql]
----
DELETE FROM Cat cat
WHERE cat.name IS NULL
----



NOTE: Since a `DELETE` statement can't have joins, implicit joins generated by deep path expressions are disallowed. Use an `EXISTS` subquery if you need to join relations.
// Note that cascading deletes are done in CTEs on PostgreSQL and DB2

=== UPDATE statement
// Limitation: no update versioned
// Note disallowance of explicit/implicit joins and refer to FROM clause section

=== INSERT-SELECT statement
// With Hibernate you can also do insert-into-select

=== RETURNING clause support

// Mention you can use DML in CTEs on PostgreSQL and DB2