== CTEs

CTEs provide a way to introduce statements into a larger query that can be reused. CTEs are like temporary entity sets/tables that are created for the scope of the query and then deleted.
A CTE normally contains a `SELECT` statement, but depending on the DBMS support, can also contain `INSERT`, `UPDATE` and `DELETE` statements.

WARNING: This feature is currently only supported with Hibernate!

Before you can define a query for a CTE, the structure of the it has to be defined in a similar manner as an entity is defined.
Don't forget to also add it to your persistence.xml so that the JPA provider can discover it.

[source,java]
----
@CTE    // from com.blazebit.persistence
@Entity // from javax.persistence
public class MyCte {

    private Long id;

    @Id // from javax.persistence
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
}
----

The difference to a normal entity is that in addition to that, the `CTE` annotation is applied which treats it like a view i.e. no DDL is generated for it.
A CTE can be defined on a top level query builder by using the link:{core_jdoc}/persistence/CTEBuilder.html#with(java.lang.Class)[`with(Class<?>)`] method.
The created CTE builder has to be finished by calling `end()` on it.

All attributes of a CTE must be bound to expressions with link:{core_jdoc}/SelectBaseCTECriteriaBuilder.html#bind(java.lang.String)[`bind()`] like in the following.

[source,java]
----
CriteriaBuilder<MyCte> cb = cbf.create(em, MyCte.class)
    .with(MyCte.class)
        .from(Cat.class, "cat")
        .bind("id").select("cat.id")
    .end();
----

NOTE: Since you can map columns multiple times in the CTE entity, it is sufficient to make sure that all columns have values bound through attribute bindings. If a column is left out, you will get an exception.

As you can see from the example, the API tries to look as much as possible like the CTE syntax as defined in the SQL-99 standard.
As for all advanced features, the query string returned by link:{core_jdoc}/persistence/Queryable.html#getQueryString()[`getQueryString()`] only represents the _logical structure_ of the whole query in a syntax that might be used one day by JPA providers to support this feature natively.

[source,sql]
----
WITH MyCte(id) AS(
    SELECT cat.id FROM Cat cat
)
SELECT myCte FROM MyCte myCte
----

[[cte-implementation-notes]]
=== Implementation notes

Currently the CTE support is only implemented for Hibernate because of the deep integration that is needed for it to work.
The integration with the persistence provider happens in the implementation of link:{core_jdoc}/persistence/spi/ExtendedQuerySupport.html[`com.blazebit.persistence.spi.ExtendedQuerySupport`]
which tries to focus on the minimal necessary methods needed for the integration to work.

In case of Hibernate, a CTE entity class is treated as if `org.hibernate.annotations.Subselect` was annotated.
Hibernate generally generates from clause elements of the form `( select * from MyCTE )` for `Subselect` entities which we replace simply by the name of the CTE.

The current implementation extracts the SQL from various template JPQL queries that are created behind the scenes.
After applying different transformations on the SQL and merging it together to a single SQL query, the new SQL replaces is used in a special JPQL query object.
The special JPQL query object is what you can finally execute. It will make use of the SQL query that was created before.

Every CTE will result in a separate JPQL query behind the scenes from which the SQL is extracted.
The SQL from the main query, together with the SQLs from the CTEs are put together to form the full SQL query.
It is that SQL, the special JPQL query receives for later execution.

NOTE: In order to support the `org.hibernate.FetchMode.SUBSELECT` this library ships with custom implementations of `org.hibernate.persister.collection.CollectionPersister`.
Custom persister implementations should be made aware of CTEs in a similar fashion to be able to make use of the fetch mode.

=== Recursive CTEs

CTEs not only provide a way to extract subqueries or use subqueries in the FROM clause, but also to implement recursive queries.

A recursive CTE is normally composed of two parts, a base query(non-recursive query) and a recursive query connected with the *SET* operator `UNION` or `UNION ALL`.
The recursive part is allowed to refer to the CTE itself.

A recursive CTE is normally evaluated in iterations

1. The base query is evaluated and the result put into a temporary work set/table
2. The recursive query operates on the work set/table data and replaces it with the newly produced data
3. When the recursive query didn't produce data, the recursion and thus the query is finished

The following illustrates how the ancestor hierarchy of an entity can be retrieved.

[source,java]
.CTE structure definition
----
@CTE    // from com.blazebit.persistence
@Entity // from javax.persistence
public class CatCte {

    private Long id;
    private Cat ancestor;

    @Id // from javax.persistence
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    @ManyToOne
    public Cat getAncestor() { return ancestor; }
    public void setAncestor(Cat ancestor) { this.ancestor = ancestor; }
}
----

[source,java]
.Recursive query
----
CriteriaBuilder<CatCte> cb = cbf.create(em, CatCte.class)
    .withRecursive(CatCte.class)
        .from(Cat.class, "cat") #<1>
        .bind("id").select("cat.id")
        .bind("ancestor").select("cat.ancestor")
        .where("id").eq(someCatId)
    .unionAll()
        .from(Cat.class, "cat")
        .from(CatCte.class, "parentCat") #<2>
        .bind("id").select("cat.id")
        .bind("ancestor").select("cat.ancestor")
        .where("id").eqExpression("parentCat.ancestor.id") #<3>
    .end();
----
<1> We start with the non-recursive query and just bind the cat attributes of the desired cat
<2> We refer to the CTE itself in the recursive query to be able to _join_ data with data of the previous iteration
<3> Only _join_ the cats that are an `ancestor` of the cats from the previous iteration

[source,sql]
.Logical representation
----
WITH RECURSIVE CatCte(id, ancestor) AS(
    SELECT cat.id, cat.ancestor FROM Cat cat WHERE cat.id = :someCatId
    UNION ALL
    SELECT cat.id, cat.ancestor FROM Cat cat, CatCte parentCat WHERE cat.id = parentCat.ancestor.id
)
SELECT catCte FROM CatCte catCte
----

This will return all the ancestors of the Cat with an id equal to *someCatId*.

=== Updatable CTEs

An updatable CTE is like a normal CTE, but the data comes from returned attributes of a DML statement.

NOTE: At this point, only PostgreSQL and DB2 support this feature.

You can start an updatable CTE with the link:{core_jdoc}/persistence/CTEBuilder.html#withReturning(java.lang.Class)[`withReturning()`] method and subsequently decide the DML statement type.
The query builder for the DML statement provides a link:{core_jdoc}/persistence/ReturningBuilder.html#returning(java.lang.String,%20java.lang.String)[`returning()`] method for binding attributes of the DML statement to a CTE attribute.

[source,java]
----
CriteriaBuilder<MyCte> cb = cbf.create(em, MyCte.class)
    .withReturning(MyCte.class)
        .delete(Cat.class, "cat")
        .where("cat.name").isNull()
        .returning("id", "cat.id")
    .end();
----

[source,sql]
----
WITH MyCte(id) AS(
    DELETE FROM Cat cat
    WHERE cat.name IS NULL
    RETURNING id
)
SELECT myCte FROM MyCte myCte
----

The query deletes cats with a `NULL` name. For every deleted cat, a temporary `MyCte` entity with the cat's id bound is created. Finally the deleted cats are queried through `MyCte`.

As you can imagine, this can be used to define very efficient data pipelines.

One problem with updatable CTEs that might come up is, that you might want to query an entity in one CTE, while also wanting to do a modification in a different CTE.
Since the visibility of changes that are done in updatable CTEs might differ from one to another DBMS, {projectname} offers a way to resolve this special case.

Let's consider the following example:

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .withReturning(MyCte.class)
        .delete(Cat.class, "cat")
        .where("cat.name").isNull()
        .returning("id", "cat.id")
    .end()
    .from(Cat.class, "theCat");
----

[source,sql]
----
WITH MyCte(id) AS(
    DELETE FROM Cat cat
    WHERE cat.name IS NULL
    RETURNING id
)
SELECT theCat FROM Cat theCat
----

Although the CTE `MyCte` is never used, it is still executed. Depending on the DBMS you are on, the `SELECT` statement will return the state before or after the `DELETE` statement happened.

WARNING: Multiple updatable CTEs for the same entity in a single query are not supported.

In order to make the `SELECT` statement portable, {projectname} provides a way to qualify a `FROM` clause element to use the _old_ or _new_ state i.e. before or after modifications happened.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .withReturning(MyCte.class)
        .delete(Cat.class, "cat")
        .where("cat.name").isNull()
        .returning("id", "cat.id")
    .end()
    .fromOld(Cat.class, "theCat");
----

[source,sql]
----
WITH MyCte(id) AS(
    DELETE FROM Cat cat
    WHERE cat.name IS NULL
    RETURNING id
)
SELECT theCat FROM OLD(Cat) theCat
----

The link:{core_jdoc}/persistence/FromBuilder.html#fromOld(java.lang.Class,%20java.lang.String)[`fromOld()`] method qualifies the `FROM` element in the query as _old_.
In the same way does link:{core_jdoc}/persistence/FromBuilder.html#fromNew(java.lang.Class,%20java.lang.String)[`fromNew()`] qualify the `FROM` element as _new_.

In general, we advise you to rethink how you do the querying when having a need for this feature. It should only be used as a last resort.

[[anchor-ctes-dbms-compatibility]]
=== DBMS compatibility

Currently there is no emulation implemented for databases that do not support CTEs natively.
CTEs are well tested with *PostgreSQL*, *DB2*, *Oracle* and *Microsoft SQL Server*. Many of the basic features work with *H2*, but beware that H2 support for CTEs is still experimental.

WARNING: We do not recommend using CTEs with H2 because of some very serious limitations. Using a CTE in an `IN` predicate or using `LIMIT` within the CTE have proven to produce wrong results. You also can't have multiple CTEs per query.

NOTE: DB2 does not support JOINs in the recursive part of a CTE: https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/com.ibm.db2z10.doc.codes/src/tpc/n345.dita

_CTEs in DML_ are uses of a CTE where the top level statement is a DML. In contrast, _Updatable CTEs_ are CTEs that *contain* DML and get their values from a `RETURNING` clause of the DML.

// TODO: When fixing #337 we could actually fallback to inlining for non-recursive CTEs on DBMS that don't support CTEs

[width="100%",options="header,footer"]
|====================
| *DBMS*     | Normal CTEs  | Recursive CTEs    | CTEs in DML  | Updatable CTEs
| PostgreSQL | yes          | yes               | yes          | yes
| MySQL      | no           | no                | no           | no
| H2         | partly       | partly            | no           | no
| Oracle     | yes          | partly            | yes          | no
| SQL Server | yes          | yes               | yes          | no
| DB2        | yes          | yes               | yes          | yes
|====================