== From clause

The `FROM` clause contains the entities which should be queried.
Normally a query will have one root entity which is why {projectname} offers a convenient factory for creating queries that select the root entity.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class);
----

The type `Cat` has multiple purposes in this case.

. It defines the result type of the query
. Creates an implicit query root with that type and the alias _cat_
. Implicitly selects _cat_

This implicit logic will help to avoid some boilerplate code in most of the cases.
The JPQL generated for such a simple query is just like you would expect

[source,sql]
----
SELECT cat
FROM Cat cat
----

As soon as a query root is added via `from()`, the implicitly created query root is removed.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .from(Person.class, "person")
    .select("person.kittens");
----

In such a query, the type `Cat` only serves the purpose of defining the query result type.

[source,sql]
----
SELECT kittens_1
FROM Person person
LEFT JOIN person.kittens kittens_1
----

Contrary to the described behavior, using the overload of the `create` method that allows to specify the alias for the query root will result in an explicit query root.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class, "myCat");
----

This is essentially a shorthand for

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .from(Cat.class, "myCat");
----

A query can also have multiple root entities which are connected with the `,` operator that essentially has the semantics of a `CROSS JOIN`.
Beware that when having multiple root entities, path expression must use absolute paths.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class, "myCat")
    .select("name");
----

The expression `name` in this case is interpreted as relative to the query root, so it is equivalent to `myCat.name`.
When having multiple query roots, the use of a relative path will lead to an exception saying that relative resolving is not allowed with multiple query roots!

=== Joins

JPQL offers support for `CROSS`, `INNER`, `LEFT` and `RIGHT JOIN` which are all well supported by {projectname}.
In contrast to JPQL, {projectname} also has a notion of implicit/default and explicit joins which makes it very convenient to write queries as can be seen a few sections later.

WARNING: `RIGHT JOIN` support is optional in JPA so we recommend not using it at all.

NOTE: In addition to joins on mapped relations, {projectname} also offers support for unrelated or entity joins offered by all major JPA providers.

==== Implicit joins

An implicit or default join is a special join that can be referred to by

. an absolute path from a root entity to an association
. alias if an explicit alias has been defined via link:{core_jdoc}/persistence/FromBuilder.html#joinDefault(java.lang.String,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinDefault()`] means

NOTE: A path is considered _absolute_ also if it is relative to the query root

The following query builder will create an implicit join for the path `kittens` when inspecting the select clause and reuse that implicit join in the where clause because of the use of an absolute path.

[source,java]
----
CriteriaBuilder<Integer> cb = cbf.create(em, Integer.class)
    .from(Cat.class)
    .select("kittens.age")
    .where("kittens.age").gt(1);
----

This will result in the following JPQL query

[source,sql]
----
SELECT kittens_1.age
FROM Cat cat
LEFT JOIN cat.kittens kittens_1
WHERE kittens_1.age > 1
----

A relation dereference like `alias.relation.property` will always result in a JOIN being added for `alias.relation`.
The exception to that is when the accessed property is the identifier property of the type of `relation` and that identifier is owned by `alias` i.e. the column is contained in the owner's table.
If the property is the identifier and the `JpaProvider` supports link:{core_jdoc}/persistence/spi/JpaProvider.html#supportsSingleValuedAssociationIdExpressions()[optimized id access],
no join is generated but instead the expression is rendered as it is `alias.relation.identifier`.

===== Model awareness

Implicit joins are a result of a path dereference or explicit fetching. A path dereference can happen in any place where an expression is expected.
An explicit fetch can be invoked on link:{core_jdoc}/persistence/FullQueryBuilder.html[`FullQueryBuilder`] instances which is the top type for
link:{core_jdoc}/persistence/CriteriaBuilder.html[`CriteriaBuilder`] and link:{core_jdoc}/persistence/PaginatedCriteriaBuilder.html[`PaginatedCriteriaBuilder`].

Every implicit join will result in a so called "model-aware" join. The model-awareness of a join is responsible for determining the join type to use.
Generally it is a good intuition to think of a model-aware join to always produce results, thus never restricting the result set but only extending it.
A model-aware join currently decides between `INNER` and `LEFT JOIN`. The `INNER JOIN` is only used if 

* The parent join is an `INNER JOIN`
* The relation is non-optional e.g. the `optional` attribute of a `@ManyToOne` or `@OneToOne` is false

NOTE: This is different from how JPQL path expressions are normally interpreted but will result in a more natural output.

If you aren't happy with the join types you can override them and even specify an alias for implicit joins via the
link:{core_jdoc}/persistence/FromBuilder.html#joinDefault(java.lang.String,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinDefault`] method and variants.
Consider the following example for illustration purposes of the implicit joins.

[source,java]
----
CriteriaBuilder<Integer> cb = cbf.create(em, Integer.class)
    .from(Cat.class)
    .select("kittens.age")
    .where("kittens.age").gt(1)
    .innerJoinDefault("kittens", "kitty");
----

The builder first creates an implicit join for `kittens` with the join type `LEFT JOIN` because a Collection can never be non-optional.
If you just had the `SELECT` clause, a `NULL` value would be produced for cats that don't have kittens.
But in this case the `WHERE` clause filters out these cats, because any comparison with `NULL` will result in `UNKNOWN` and thus `FALSE`.

NOTE: Null-aware predicates like `IS NULL` are obviously an exception to this.

The last statement will take the default/implicit join for the path `kittens`, set the join type to `INNER` and the alias to `kitty`.

WARNING: Although the generated aliases for implicit joins are deterministic, they might change over time so you should never use them to refer to implicit joins.
Always use the full path to the join relation or define an alias and use that instead!

==== Explicit joins

Explicit joins are different from implicit/default joins in a sense that they are only accessible through their alias. You can have only one default join which is identified by it's absolute path,
but multiple explicit joins as these are identified by their alias. This means that you can also join a relation multiple times with different aliases.

You can create explicit joins with the link:{core_doc]/persistence/FromBuilder.html#join(java.lang.String,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`join()`] method and variants.
The following shows explicit and implicit joins used together.

[source,java]
----
CriteriaBuilder<Integer> cb = cbf.create(em, Integer.class)
    .from(Cat.class)
    .select("kittens.age")
    .where("kitty.age").gt(1)
    .innerJoin("kittens", "kitty");
----

This query will in fact create two joins. One for the explicitly inner joined `kittens` with the alias `kitty` and another for the implicitly left joined `kittens` used in the `SELECT` clause.
The resulting JPQL looks like the following

[source,sql]
----
SELECT kittens_1.age
FROM Cat cat
INNER JOIN cat.kittens kitty
LEFT JOIN cat.kittens kittens_1
WHERE kitty.age > 1
----

==== Fetched joins

Analogous to the `FETCH` keyword in JPQL, you can specify for every join node of a link:{core_jdoc}/persistence/FullQueryBuilder.html[`FullQueryBuilder`] if it should be fetched.
Every link:{core_jdoc}/persistence/FromBuilder.html#join(java.lang.String,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`join()`] method variant comes with a partner method,
that does fetching for the joined path. In addition to that, there is also a simple link:{core_jdoc}/persistence/FullQueryBuilder.html#fetch(java.lang.String...)[`fetch()`] method which can be provided with absolute paths to relations.
These relations are then implicit/default join fetched, i.e. a default join node with fetching enabled is created for every relation.

TIP: You can make use of deep paths like `kittens.kittens` which will result in fetch joining two levels of kittens.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .from(Cat.class)
    .leftJoinFetch("father", "dad")
    .whereOr()
        .where("dad").isNull()
        .where("dad.age").gt(1)
    .endOr()
    .fetch("kittens.kittens", "mother");
----

The `father` relation is left join fetched and given an alias which is then used in the `WHERE` clause. Two levels of `kittens` and the `mother` relation are join fetched.

[source,sql]
----
SELECT cat
FROM Cat cat
LEFT JOIN FETCH cat.father dad
LEFT JOIN FETCH cat.kittens kittens_1
LEFT JOIN FETCH kittens_1.kittens kittens_2
LEFT JOIN FETCH cat.mother mother_1
WHERE dad IS NULL
   OR dad.age > 1
----

WARNING: Although the JPA spec does not specifically allow aliasing fetch joins, every major JPA provider supports this.

When doing a scalar select instead of a query root select, {projectname} automatically adapts the fetches to the new fetch owners.

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class)
    .from(Cat.class)
    .fetch("father.kittens")
    .select("father");
----

In this case we fetch the `father` relation and the `kittens` of the `father`. By also selecting the `father` relation, the fetch owner changes from the query root to the `father`.
This has the effect, that the `father` is not fetch joined, as that would be invalid.

[source,sql]
----
SELECT father_1
FROM Cat cat
LEFT JOIN cat.father father_1
LEFT JOIN FETCH father_1.kittens kittens_1
----

==== Array joins

Array joins are an extension to the JPQL grammar which offer a convenient way to create joins with an `ON` clause condition.
An array join expression is a path expression followed by an opening bracket, the index expression and then the closing bracket e.g. `arrayBase[indexPredicateOrExpression]`.

The type of the `arrayBase` expression must be an association. If it is an indexed `List` e.g. uses a `@OrderColumn` or a `Map` it is possible to use an expression.
In case of an indexed list, the type of the `indexPredicateOrExpression` must be numeric. For maps, the type must match the map key type as defined in the entity.

[source,java]
----
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .from(Cat.class)
    .select("localizedName[:language]")
    .where("localizedName[:language]").isNotNull();
----

Such a query will result in the following JPQL

[source,sql]
----
SELECT localizedName_language
FROM Cat cat
LEFT JOIN cat.localizedName localizedName_language
       ON KEY(localizedName_language) = :language
WHERE localizedName_language IS NOT NULL
----

The relation `localizedName` is assumed to be a map of type `Map<String, String>` which maps a language code to a localized name.

The more general approach is to use a predicate expression that allows to filter an association.

[source,java]
----
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .from(Cat.class)
    .select("kittens[age > 18].id")
    .select("kittens[age > 18].name");
----

Such a query will result in the following JPQL

[source,sql]
----
SELECT kittens_age___18.id, kittens_age___18.name
FROM Cat cat
LEFT JOIN cat.kittens kittens_age___18
       ON kittens_age___18.age > 18
----

Note that it is also possible to use an entity name as base expression for an array expression, which is called an <<entity-array-expressions,_entity array expression_>>.

[source,java]
----
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .from(Cat.class)
    .select("Cat[age > 18].id")
    .select("Cat[age > 18].name");
----

Such a query will result in the following JPQL

[source,sql]
----
SELECT kittens_age___18.id, kittens_age___18.name
FROM Cat cat
LEFT JOIN Cat Cat___age___18
       ON kittens_age___18.age > 18
----

NOTE: In case of array expressions, the generated implicit/default join node is identified not only by the absolute path, but also by the index expression.

==== Correlated joins

JPQL allows subqueries to refer to a relation based on a join alias of the outer query within the from clause, also known as correlated join.
A correlated join in {projectname} can be done when link:{core_jdoc}/persistence/SubqueryInitiator.html#from(java.lang.String)[initiating a subquery]
or be added as link:{core_jdoc}/persistence/BaseSubqueryBuilder.html#from(java.lang.String)[cross join] to an existing subquery builder.

[source,java]
----
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .from(Cat.class, "c")
    .selectSubquery()
        .from("c.kittens", "kitty")
        .select("COUNT(kitty.id)")
    .end();
----

Such a query will result in the following JPQL

[source,sql]
----
SELECT
    (
        SELECT COUNT(kitty.id)
        FROM c.kittens kitty
    )
FROM Cat c
----

NOTE: Although JPA does not mandate the support for subqueries in the `SELECT` clause, every major JPA provider supports it.

You can even use the `OUTER` function or macros within the correlation join path!

[source,java]
----
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .from(Cat.class, "c")
    .selectSubquery()
        .from("OUTER(kittens)", "kitty")
        .select("COUNT(kitty.id)")
    .end();
----

This will result in the same JPQL as before as `OUTER` will refer to the query root of the outer query.

[source,sql]
----
SELECT
    (
        SELECT COUNT(kitty.id)
        FROM c.kittens kitty
    )
FROM Cat c
----

[[anchor-entity-joins]]
==== Entity joins

An entity join is a type of join for unrelated entities, in the sense that no JPA mapping is required to join the entities.
Entity joins are quite useful, especially when information from separate models(i.e. models that have no static dependency on each other) should be queried.

NOTE: Entity joins are only supported in newer versions of JPA providers(Hibernate 5.1+, EclipseLink 2.4+, DataNucleus 5+)

Imagine a query that reports the count of people that are older than a cat for each cat

[source,java]
----
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .from(Cat.class, "c")
    .leftJoinOn(Person.class, "p")
        .on("c.age").ltExpression("p.age")
    .end()
    .select("c.name")
    .select("COUNT(p.id)")
    .groupBy("c.id", "c.name");
----

The JPQL representation looks just as expected

[source,sql]
----
SELECT c.name, COUNT(p.id)
FROM Cat c
LEFT JOIN Person p
       ON c.age < p.age
GROUP BY c.id, c.name
----

Entity joins normally link:{core_jdoc}/persistence/FromBuilder.html#joinOn(java.lang.String,%20java.lang.Class,%20java.lang.String,%20com.blazebit.persistence.JoinType)[require a base alias]
but link:{core_jdoc}/persistence/FromBuilder.html#joinOn(java.lang.Class,%20java.lang.String,%20com.blazebit.persistence.JoinType)[default to the query root] when only a single query root is available.

NOTE: `INNER` entity joins don't need support from the JPA provider because these are rewritten to a JPQL compliant `CROSS JOIN` if necessary.

=== On clause

The `ON` clause is a filter predicate similar to the `WHERE` clause, but is evaluated while joining to restrict the joined elements.
In case of `INNER` joins the `ON` clause has the same effect as when putting the predicate into the `WHERE` clause.
However `LEFT` joins won't filter out objects from the source even if the predicate doesn't match any joinable object, but instead will produce a `NULL` value for the joined element.

The `ON` clause is used when using array joins to restrict the key of a join to the index expression.

WARNING: Since the `ON` clause is only supported as of JPA 2.1, the usage with JPA 2.0 providers that have no equivalent vendor extension will fail.

The `ON` clause can be constructed by setting a JPQL predicate expression with `setOnExpression()` or by using the <<predicate-builder,predicate builder>, Predicate Builder API>>.

[cols="a,a"]
|===
|setOnExpression() |Predicate Builder API

|[source,java]
----
CriteriaBuilder<String> cb =
    cbf.create(em, String.class)
    .from(Cat.class)
    .select("l10nName")
    .leftJoinOn("localizedName", "l10nName")
      .setOnExpression("KEY(l10nName) = :lang")
    .where("l10nName").isNotNull();
----

|[source,java]
----
CriteriaBuilder<String> cb =
    cbf.create(em, String.class)
    .from(Cat.class)
    .select("l10nName")
    .leftJoinOn("localizedName", "l10nName")
        .on("KEY(l10nName)").eq(":lang")
    .end()
    .where("l10nName").isNotNull();
----
|===

The resulting JPQL looks as expected

[source,sql]
----
SELECT localizedNameForLanguage
FROM Cat cat
LEFT JOIN cat.localizedName l10nName
       ON KEY(l10nName) = :lang
WHERE l10nName IS NOT NULL
----

[[anchor-values-clause]]
=== VALUES clause

The `VALUES` clause is similar to the SQL `VALUES` clause in the sense that it allows to define a temporary set of objects for querying.
There are 3 different types of values for which a `VALUES` clause can be created

* Basic values (Integer, String, etc.)
* Managed values (Entities, Embeddables, CTEs)
* Identifiable values (Entities, CTEs)

For query caching reasons, a `VALUES` clause has a fixed number of elements. If you bind a collection that has a smaller size, behind the scenes the rest is filled up with `NULL` values which are filtered out by a `WHERE` clause automatically.
Trying to bind a collection with a larger size will lead to an exception at bind time.

The `VALUES` clause is a feature that can be used for doing efficient batching. The number of elements can serve as batch size. Processing a collection iteratively and binding subsets to a query efficiently reuses query caches.
For one-shot or rarely executed queries it might not be necessary to implement batching.
In such cases use one of the link:{core_jdoc}/persistence/FromBuilder.html#fromValues(java.lang.Class,%20java.lang.String,%20java.util.Collection)[overloads] that use the collection size as number of elements.

The join alias that must be defined for a `VALUES` clause is reused as alias for the parameter to bind values.

[source,java]
----
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .fromValues(String.class, "myValue", 10)
    .select("myValue")
    .setParameter("myValue", valueCollection);
----

NOTE: For some cases it might be better to make use of <<entity-functions,entity functions>> instead of a `VALUES`

==== Basic values

The following basic value types are supported

* `Boolean`
* `Byte`
* `Short`
* `Integer`
* `Long`
* `Float`
* `Double`
* `Character`
* `String`
* `BigInteger`
* `BigDecimal`
* `java.sql.Time`
* `java.sql.Date`
* `java.sql.Timestamp`
* `java.util.Date`
* `java.util.Calendar`

via the link:{core_jdoc}/persistence/FromBuilder.html#fromValues(java.lang.Class,%20java.lang.String,%20int)[fromValues(Class elementType, String alias, int size)] method.

[source,java]
----
Collection<String> valueCollection = Arrays.asList("value1", "value2");
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .fromValues(String.class, "myValue", valueCollection)
    .select("myValue");
----

The resulting logical JPQL doesn't include individual parameters, but specifies the count of the values. The alias of the values clause from item also represents the parameter name.

[source,sql]
----
SELECT myValue
FROM String(2 VALUES) myValue
----

Behind the scenes, a type called `ValuesEntity` is used to be able to implement the VALUES clause.

For further information on `TREAT` functions, take a look at the <<treat-functions,JPQL functions>> chapter.

==== Non-Standard basic values

To support non-standard basic types the link:{core_jdoc}/persistence/FromBuilder.html#fromValues(java.lang.Class,%20java.lang.String,%20java.lang.String,%20int)[fromValues(Class entityType, String attribute, String alias, int size)] method
has to be used which will determine the proper SQL type based on the SQL type of the specified entity attribute.

[source,java]
----
Collection<String> valueCollection = Arrays.asList("value1", "value2");
CriteriaBuilder<String> cb = cbf.create(em, String.class)
    .fromValues(Cat.class, "name", "myValue", valueCollection)
    .select("myValue");
----

The logical JPQL encodes this as

[source,sql]
----
SELECT myValue
FROM String(2 VALUES LIKE Cat.name) myValue
----

==== Managed values

Managed values are objects of a JPA managed type i.e. entities or embeddables. A `VALUES` clause for such types will include *all* properties of that type,
so be careful when using this variant. For using only the _id_ part of a managed type, take a look at the <<identifiable-values,identifiable values>> variant.
If using all properties of an entity or embeddable is not appropriate for you, you should consider creating a custom <<ctes,_CTE entity_>> that covers only the subset of properties you are interested in
and finally convert your entity or embeddable object to that new type so it can be used with the `VALUES` clause.

Let's look at an example

[source,java]
----
@Embeddable
class MyEmbeddable {
    private String property1;
    private String property2;
}
----

The embeddable defines 2 properties and a `VALUES` query for objects of that type might look like this

[source,java]
----
Collection<MyEmbeddable> valueCollection = ...
CriteriaBuilder<MyEmbeddable> cb = cbf.create(em, MyEmbeddable.class)
    .fromValues(MyEmbeddable.class, "myValue", valueCollection)
    .select("myValue");
----

The JPQL for such a query looks roughly like the following

[source,sql]
----
SELECT myValue
FROM MyEmbeddable(1 VALUES) myValue
----

==== Identifiable values

Identifiable values are also objects of a JPA managed type, but restricted to identifiable managed types i.e. no embeddables.
Every entity and <<ctes,_CTE entity_>> is an identifiable managed type and can thus be used in
link:{core_jdoc}/persistence/FromBuilder.html#fromIdentifiableValues(java.lang.Class,%20java.lang.String,%20java.util.Collection)[`fromIdentifiableValues()`].

The main difference to the link:{core_jdoc}/persistence/FromBuilder.html#fromValues(java.lang.Class,%20java.lang.String,%20java.util.Collection)[managed values variant]
is that only the identifier properties of the objects are bound instead of all properties.

Let's look at an example

[source,java]
----
Collection<Cat> valueCollection = ...
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .fromIdentifiableValues(Cat.class, "cat", valueCollection)
    .select("cat.id");
----

The JPQL for such a query looks roughly like the following

[source,sql]
----
SELECT cat.id
FROM Cat.id(1 VALUES) cat
----

The values parameter "cat" will still expect instances of the type `Cat`, but will only bind the id attribute values.
This also works for embedded ids and access to the embedded values works just like expected, by dereferencing the embeddable further i.e. `alias.embeddable.property`

WARNING: When using the identifiable values, only the id values are available for the query. Using any other property will lead to an exception.

=== Before and after DML in CTEs

When using <<updatable-ctes,DML in CTEs>> it depends on the DBMS what state a `FROM` element might give.
Normally this is not problematic as it is rarely necessary to do DML and a `SELECT` for the same entity in one query.
When it is necessary to do that, it is strongly advised to make use of link:{core_jdoc}/persistence/FromBuilder.html#fromOld(java.lang.Class)[`fromOld()`]
or link:{core_jdoc}/persistence/FromBuilder.html#fromNew(java.lang.Class)[`fromNew()`] to use the state before or after side-effects happen.

For example usage and further information, take a look into the <<updatable-ctes,Updatable CTEs chapter>>

=== Subquery in FROM clause

In SQL, a from clause item must be a relation which is usually a table name but can also be a subquery, yet most ORMs do not support that directly.
{projectname} implements support for subqueries in the `FROM` clause by requiring the return type of a subquery to be an entity or CTE type.
This is similar to how inlined CTEs work and in fact, under the hood, CTE builders are used to make this feature work. For more information about CTEs, go to the <<CTEs,CTE documentation section>>.

Before a subquery can be constructed, one has to think of an entity or CTE type that represents the result of the subquery.
Consider the following CTE entity as an example.

[source,java]
----
@CTE
@Entity
class ResultCte {
    @Id
    private Long id;
    private String name;
}
----

This CTE entity can then be used as result type for a subquery in link:{core_jdoc}/persistence/FromBaseBuilder.html#fromSubquery(java.lang.Class,%20java.lang.String)[`fromSubquery()`].

[source,java]
----
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .fromSubquery(ResultCte.class, "r")
        .from(Cat.class, "subCat")
        .bind("id").select("id")
        .bind("name").select("name")
        .orderByDesc("age")
        .orderByDesc("id")
        .setMaxResults(5)
    .end()
    .select("r.id");
----

The example doesn't really make sense, it just tries to show off the possibilities.
The JPQL for such a query looks roughly like the following

[source,sql]
----
SELECT r.id
FROM ResultCte(
    SELECT subCat.id, subCat.name
    FROM Cat subCat
    ORDER BY subCat.age DESC, subCat.id DESC
    LIMIT 5
) r(id, name)
----

Using a dedicated entity or CTE class for a subquery result and binding every attribute might make sense for some cases,
but most of the time, it is sufficient to re-bind all entity attributes again i.e. the result type matches the query root type `Cat`.
To help with writing such queries, the link:{core_jdoc}/persistence/FromBaseBuilder.html#fromEntitySubquery(java.lang.Class,%20java.lang.String)[`fromEntitySubquery()`] method can be used.
Databases are pretty good at eliminating unnecessary/unused projections in such scenarios, so it's no big deal to use this short-cut if applicable.

[source,java]
----
CriteriaBuilder<Long> cb = cbf.create(em, Long.class)
    .fromEntitySubquery(Cat.class, "r")
        .orderByDesc("age")
        .orderByDesc("id")
        .setMaxResults(5)
    .end()
    .select("r.id");
----

will result in something like the following:

[source,sql]
----
SELECT r.id
FROM Cat(
    SELECT r_1.age, r_1.father.id, r_1.id, r_1.mother.id, r_1.name
    FROM Cat r_1
    ORDER BY r_1.age DESC, r_1.id DESC
    LIMIT 5
) r(age, father.id, id, mother.id, name)
----

As can be seen, all _owned_ entity attributes of the type `Cat` are bound again.

Apart from the `fromXXX` methods there is also support for joining such subqueries via
the link:{core_jdoc}/persistence/FromBuilder.html#joinOnSubquery(java.lang.Class,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinOnSubquery()`]
and link:{core_jdoc}/persistence/FromBuilder.html#joinOnEntitySubquery(java.lang.Class,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinOnEntitySubquery()`]
methods or the join type specific variants.

=== Lateral subquery join

{projectname} offers support for doing lateral joins via the methods
link:{core_jdoc}/persistence/FromBuilder.html#joinLateralOnSubquery(java.lang.Class,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinLateralOnSubquery()`]
and link:{core_jdoc}/persistence/FromBuilder.html#joinLateralOnEntitySubquery(java.lang.Class,%20java.lang.String,%20java.lang.String,%20com.blazebit.persistence.JoinType)[`joinLateralOnEntitySubquery()`].
A lateral join, which might also be known as _cross apply_ or _outer apply_, allows to refer to aliases on the _left side_ of the subquery i.e. the alias of the join base.
Such a join is like a correlated subquery for the `FROM` clause.

[source,java]
----
CriteriaBuilder<Tuple> cb = cbf.create(em, Tuple.class)
    .from(Cat.class, "c")
    .leftJoinLateralOnEntitySubquery("c.kittens", "topKitten", "kitten")
        .orderByDesc("age")
        .orderByDesc("id")
        .setMaxResults(5)
    .end()
        .on("1").eqExpression("1")
    .end()
    .select("c.name")
    .select("COUNT(topKitten.id)");
----

The example query shows a special feature of lateral joins, which is the possibility to correlate a collection for a lateral join.
This could also have been written by correlating an entity type and defining the correlation for the collection in the `WHERE` clause manually.

The resulting JPQL might look like the following:

[source,sql]
----
SELECT c.name, COUNT(topKitten.id)
FROM Cat c
LEFT JOIN LATERAL Cat(
    SELECT kitten.age, kitten.father.id, kitten.id, kitten.mother.id, kitten.name
    FROM Cat kitten
    ORDER BY kitten.age DESC, kitten.id DESC
    LIMIT 5
) topKitten(age, father.id, id, mother.id, name) ON 1=1
GROUP BY c.name
----

Note that lateral joins only work for inner and left joins. Also, not all databases support lateral joins.
H2 and HSQL do not support that feature. MySQL only supports this since version 8. Oracle supports this since version 12.
