:linkattrs:

= Documentation
:page: documentation
:jbake-type: index
:jbake-status: published

[.bTop.clearfix]
== Documentation, articles and presentations

[.tCenter]
Currently the documentation consists of reference manuals only but will be extended with how-to articles soon. This section also lists articles and presentations, so if you want to get listed, let us know!

=== Articles

https://blazebit.com/tags/blaze-persistence.html[*Blazebit blog posts*, window="_blank"]::
Blog posts from the creators of blaze-persistence on the Blazebit blog

=== Reference and guides

[horizontal]
link:documentation/core/manual/en_US/index.html[Core Reference, window="_blank"]::
The reference documentation for the Core module
+
[.versions]
//link:documentation/1.7/core/manual/en_US/index.html[Development 1.7, window="_blank", role="development-version"]
link:documentation/1.6/core/manual/en_US/index.html[Latest stable 1.6, window="_blank", role="stable-version"]
Older
link:documentation/1.5/core/manual/en_US/index.html[1.5, window="_blank"],
link:documentation/1.4/core/manual/en_US/index.html[1.4, window="_blank"],
link:documentation/1.3/core/manual/en_US/index.html[1.3, window="_blank"],
link:documentation/1.2/core/manual/en_US/index.html[1.2, window="_blank"]

link:documentation/entity-view/manual/en_US/index.html[Entity View Reference, window="_blank"]::
The reference documentation for the Entity View module
+
[.versions]
//link:documentation/1.7/entity-view/manual/en_US/index.html[Development 1.7, window="_blank", role="development-version"]
link:documentation/1.6/entity-view/manual/en_US/index.html[Latest stable 1.6, window="_blank", role="stable-version"]
Older
link:documentation/1.5/entity-view/manual/en_US/index.html[1.5, window="_blank"],
link:documentation/1.4/entity-view/manual/en_US/index.html[1.4, window="_blank"],
link:documentation/1.3/entity-view/manual/en_US/index.html[1.3, window="_blank"],
link:documentation/1.2/entity-view/manual/en_US/index.html[1.2, window="_blank"]

https://github.com/Blazebit/blaze-persistence#core-quick-start[*Core quickstart*, window="_blank"]::
A simple quickstart section with a usage example for the Core module

https://github.com/Blazebit/blaze-persistence#entity-view-usage[*Entity View quickstart*, window="_blank"]::
A simple quickstart section with a usage example for the Entity View module

=== Presentations

https://www.meetup.com/de-DE/Java-Vienna/events/263596528[Java Vienna Meetup 2019-12-16]::
https://www.slideshare.net/blazebitbeikov/blazepersistence-graphql-high-performance-querying-and-relay-pagination-javavienna-16122019[Blaze-Persistence GraphQL - High performance querying and Relay pagination] was a talk by Christian that introduces to GraphQL and the Relay specification and how Blaze-Persistence Entity Views with the new GraphQL integration makes developing super fast with high performance. The demo code can be found on https://github.com/Blazebit/blaze-persistence-presentation/tree/master/graphql-support-relay-pagination/demo[GitHub]

https://www.meetup.com/de-DE/Java-Vienna/events/256644900[Java Vienna Meetup 2018-12-03]::
https://www.slideshare.net/blazebitbeikov/entity-views-not-your-fathers-dtos-javaviennameetup-20181203[Entity Views - Not your father's DTOs] was a talk by Christian that uncovers the problems with traditional DTO approaches and how Blaze-Persistence Entity Views can help you overcome these issues. The demo code can be found on https://github.com/Blazebit/blaze-persistence/tree/main/examples/spring-data-webmvc[GitHub]

https://www.meetup.com/de-DE/ViennaDB-The-Austrian-Database-Meetup-Group/events/239381170[ViennaDB Meetup 2017-05-22]::
Christian gave an updated https://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-viennadb20170522[introduction talk] with a special focus on how Entity Views and Keyset pagination work internally. https://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-viennadb20170522[Slides] and demo code are https://github.com/Blazebit/blaze-persistence-presentation/tree/viennadb-2017-05-22[tagged on Github]

https://www.meetup.com/Java-Vienna/events/234641121[JSUG/Java Vienna Meetup 2016-11-14]::
Moritz and Christian gave an http://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-jsug20161114[introduction talk] of Blaze-Persistence and received a lot of good feedback. http://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-jsug20161114[Slides] and demo code are https://github.com/Blazebit/blaze-persistence-presentation/tree/jug-2016-11-14[tagged on Github]