:linkattrs:

= Documentation
:page: documentation
:jbake-type: index
:jbake-status: published

[.bTop.clearfix]
== Documentation, articles and presentations

[.tCenter]
Currently the documentation consists of reference manuals only but will be extended with how-to articles soon. This section also lists articles and presentations, so if you want to get listed, let us know!

=== Articles

https://blazebit.com/tags/blaze-persistence.html[*Blazebit blog posts*, window="_blank"]::
Blog posts from the creators of blaze-persistence on the Blazebit blog

=== Reference and guides

[horizontal]
link:documentation/core/manual/en_US/index.html[Core Reference, window="_blank"]::
The reference documentation for the Core module
+
[.versions]
link:documentation/1.3/core/manual/en_US/index.html[Development 1.3, window="_blank", role="development-version"]
link:documentation/1.2/core/manual/en_US/index.html[Latest stable 1.2, window="_blank", role="stable-version"]
//Older
//link:documentation/1.3/core/manual/en_US/index.html[1.3, window="_blank"], 
//link:documentation/1.2/core/manual/en_US/index.html[1.2, window="_blank"]

link:documentation/entity-view/manual/en_US/index.html[Entity View Reference, window="_blank"]::
The reference documentation for the Entity View module
+
[.versions]
link:documentation/1.3/entity-view/manual/en_US/index.html[Development 1.3, window="_blank", role="development-version"]
link:documentation/1.2/entity-view/manual/en_US/index.html[Latest stable 1.2, window="_blank", role="stable-version"]
//Older
//link:documentation/1.3/entity-view/manual/en_US/index.html[1.3, window="_blank"], 
//link:documentation/1.2/entity-view/manual/en_US/index.html[1.2, window="_blank"]

https://github.com/Blazebit/blaze-persistence#core-quick-start[*Core quickstart*, window="_blank"]::
A simple quickstart section with a usage example for the Core module

https://github.com/Blazebit/blaze-persistence#entity-view-usage[*Entity View quickstart*, window="_blank"]::
A simple quickstart section with a usage example for the Entity View module

=== Presentations

https://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-viennadb20170522[ViennaDB Meetup 2017-05-22]::
Christian gave an updated https://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-viennadb20170522[introduction talk] with a special focus on how Entity Views and Keyset pagination work internally. https://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-viennadb20170522[Slides] and demo code are https://github.com/Blazebit/blaze-persistence-presentation/tree/viennadb-2017-05-22[tagged on Github]

https://www.meetup.com/Java-Vienna/events/234641121[JSUG/Java Vienna Meetup 2016-11-14]::
Moritz and Christian gave an http://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-jsug20161114[introduction talk] of Blaze-Persistence and received a lot of good feedback. http://www.slideshare.net/blazebitbeikov/blazepersistence-introduction-jsug20161114[Slides] and demo code are https://github.com/Blazebit/blaze-persistence-presentation/tree/jug-2016-11-14[tagged on Github]