== Getting started

This is a step-by-step introduction about how to get started with the entity view module of {projectname}.

The entity view module requires the {projectname} core so if you have not read the getting started
guide for the link:{core_doc}[core] yet, you might want to start your reading there.

[[getting-started-setup]]
=== Setup

As already described in the link:{core_doc}#getting-started-setup[core module setup], every module depends on the core module.
So if you haven't setup the core module dependencies yet, get back here when you did.

To make use of the entity view module, you require all artifacts from the _entity-view_ directory of the distribution.
CDI and Spring users can find integrations in _integration/entity-view_ that give a good foundation for configuring for these environments.

Spring Data users can find a special integration in _integration/entity-view_ which is described in more detail in a later <<spring-data-integration,chapter>>.
This integration depends on all artifacts of the _jpa-criteria_ module.

==== Maven setup

We recommend you introduce a version property for {projectname} which can be used for all artifacts.

[source,xml]
[subs="verbatim,attributes"]
----
<properties>
    <blaze-persistence.version>{version}</blaze-persistence.version>
</properties>
----

The required dependencies for the entity view module are

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-entity-view-api</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-entity-view-impl</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

Depending on the environment, there are some integrations that help you with configuration

[[maven-setup-cdi-integration]]
===== CDI integration

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-entity-view-cdi</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

[[maven-setup-spring-integration]]
===== Spring integration

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-entity-view-spring</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

[[maven-setup-spring-data-integration]]
===== Spring Data integration

When you work with Spring Data you can additionally have first class integration by using the following dependencies.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-2.0</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

If you still work with Spring Data 1.x you will have to use a different integration as Spring Data 2.x changed quite a bit.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-1.x</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

NOTE: The Spring Data integration depends on the _jpa-criteria_ module

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-jpa-criteria-api</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-jpa-criteria-impl</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

If a JPA provider that does not implement the JPA 2.1 specification like Hibernate 4.2 or OpenJPA is used, the following compatibility dependency is also required.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-jpa-criteria-jpa-2-compatibility</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

[[anchor-environment]]
=== Environments

The entity view module of {projectname} is usable in Java EE, Spring as well as in Java SE environments.

[[environments-java-se]]
==== Java SE

In a Java SE environment the `EntityViewConfiguration` as well as the `EntityViewManager` must
be created manually as follows:

[source,java]
----
EntityViewConfiguration cfg = EntityViews.createDefaultConfiguration();
cfg.addEntityView(EntityView1.class);
// Add some more
cfg.addEntityView(EntityViewn.class);
EntityViewManager evm = cfg.createEntityViewManager(criteriaBuilderFactory);
----

As you can see, the `EntityViewConfiguration` is used to register all the entity
view classes that you want to make accessible within the an `EntityViewManager`.

NOTE: You may create multiple `EntityViewManager` instances with potentially different
configurations.

[[environments-java-ee]]
==== Java EE

For usage with CDI the integration module _blaze-persistence-integration-entity-view-cdi_ provides a CDI
extension which takes over the task of creating and providing an `EntityViewConfiguration`
from which an `EntityViewManager` can be created like following example shows.

[source,java]
----
@Singleton // from javax.ejb
@Startup   // from javax.ejb
public class EntityViewManagerProducer {

    // inject the configuration provided by the cdi integration
    @Inject
    private EntityViewConfiguration config;
    
    // inject the criteria builder factory which will be used along with the entity view manager
    @Inject
    private CriteriaBuilderFactory criteriaBuilderFactory;

    private EntityViewManager evm;
    
    @PostConstruct
    public void init() {
        // do some configuration
        evm = config.createEntityViewManager(criteriaBuilderFactory);
    }

    @Produces
    @ApplicationScoped
    public EntityViewManager createEntityViewManager() {
        return evm;
    }
}
----

The CDI extension collects all the entity views classes and provides a producer for the pre-configured `EntityViewConfiguration`.

[[environments-cdi]]
==== CDI

If EJBs aren't available, the `EntityViewManager` can also be configured in a CDI 1.1 specific way similar to the Java EE way.

[source,java]
----
@ApplicationScoped
public class EntityViewManagerProducer {

    // inject the configuration provided by the cdi integration
    @Inject
    private EntityViewConfiguration config;

    // inject the criteria builder factory which will be used along with the entity view manager
    @Inject
    private CriteriaBuilderFactory criteriaBuilderFactory;

    private volatile EntityViewManager evm;

    public void init(@Observes @Initialized(ApplicationScoped.class) Object init) {
        // do some configuration
        evm = config.createEntityViewManager(criteriaBuilderFactory);
    }

    @Produces
    @ApplicationScoped
    public EntityViewManager createEntityViewManager() {
        return evm;
    }
}
----

[[anchor-environment-spring]]
==== Spring

You have to enable the Spring entity-views integration via annotation based config or XML based config and you can also mix those two types of configuration:

Annotation Config

[source, java]
----
@Configuration
@EnableEntityViews("my.entityviews.base.package")
public class AppConfig {
}
----

XML Config

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:ev="http://persistence.blazebit.com/view/spring"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
        http://persistence.blazebit.com/view/spring http://persistence.blazebit.com/view/spring/spring-entity-views-1.2.xsd">

    <ev:entity-views base-package="my.entityviews.base.package"/>

</beans>
----

The Spring integration collects all the entity views classes in the specified base-package and provides the pre-configured `EntityViewConfiguration` for injection.
This configuration is then used to create a `EntityViewManager` which should be provided as bean.

[source, java]
----
@Configuration
public class BlazePersistenceConfiguration {

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    // inject the criteria builder factory which will be used along with the entity view manager
    public EntityViewManager createEntityViewManager(CriteriaBuilderFactory cbf, EntityViewConfiguration entityViewConfiguration) {
        return entityViewConfiguration.createEntityViewManager(cbf);
    }
}
----

[[supported-java-runtimes]]
=== Supported Java runtimes

The entity view module like all other modules generally follows what has already been stated in the link:{core_doc}#supported-java-runtimes[core moduel documentation].

Automatic module names for modules.

|===
|Module |Automatic module name

|Entity View API
|com.blazebit.persistence.view

|Entity View Impl
|com.blazebit.persistence.view.impl

|===

=== Supported environments/libraries

Generally, we support the usage in Java EE 6+ or Spring 4+ applications.

The following table outlines the supported library versions for the integrations.

|===
|Module |Automatic module name |Minimum version |Supported versions

|CDI integration
|com.blazebit.persistence.integration.view.cdi
|CDI 1.0
|1.0, 1.1, 1.2

|Spring integration
|com.blazebit.persistence.integration.view.spring
|Spring 4.3
|4.3, 5.0

|DeltaSpike Data integration
|com.blazebit.persistence.integration.deltaspike.data
|DeltaSpike 1.7
|1.7, 1.8

|Spring Data integration
|com.blazebit.persistence.integration.spring.data
|Spring Data 1.11
|1.11, 2.0

|Spring Data Rest integration
|com.blazebit.persistence.integration.spring.data.rest
|Spring Data 1.11, Spring MVC 4.3
|Spring Data 1.11 + Spring MVC 4.3, Spring Data 2.0 + Spring MVC 5.0
|===

=== First entity view query

This section is supposed to give you a first feeling of how to use entity views.
For more detailed information, please see the subsequent chapters.

NOTE: In the following we suppose `cbf`, `em` and `evm` to refer to an instance of `CriteriaBuilderFactory`, 
JPA's `EntityManager` and `EntityViewManager`, respectively.
Take a look at the <<anchor-environment,environments>> chapter for how to obtain an `EntityViewManager`.

An entity view can be thought of as the ORM world's dual to a database table view.
It enables the user to query just a subset of an entity's fields. This enables
developers to only query what they actually need for their current use case, thereby
reducing network traffic and improving performance.

Let's start with a very simple example. Assume that in our application we want to
display a list of the names of all the cats in our database. Using entity views
we would first define a new view for this purpose:

[source,java]
----
@EntityView(Cat.class)
public interface CatNameView {

    @IdMapping
    public Long getId();

    public String getName();
    
}
----

The usage of the `CatNameView` could look like this:

[source,java]
----
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class);
CriteriaBuilder<CatNameView> catNameBuilder = evm.applySetting(EntityViewSetting.create(CatNameView.class), cb);
List<CatNameView> catNameViews = catNameBuilder.getResultList();
----

Of course, you can apply further restrictions to your query by `CriteriaBuilder` means.
E.g. you could avoid duplicate names in the above example by calling `groupBy()` on the
CriteriaBuilder at any point after its creation.

By default the abstract getter methods in the view definition map to same named entity fields.
So the `getName()` getter in the above example actually triggers querying
of the `name` field. If we want to use a different name for the getter method we would
have to add an additional `@Mapping` annotation:

[source,java]
----
@EntityView(Cat.class)
public interface CatNameView {

    @IdMapping
    public Long getId();

    @Mapping("name")
    public String getCatName();
    
}
----

Of course, it is also possible to combine various views via inheritance.

[source,java]
----
@EntityView(Cat.class)
public interface CatKittens {

    @IdMapping
    public Long getId();

    public List<Kitten> getKittens();
    
}

@EntityView(Cat.class)
public interface CatNameView {

    @IdMapping
    public Long getId();

    @Mapping("name")
    public String getCatName();
    
}

@EntityView(Cat.class)
public interface CombinedView extends CatKittens, CatNameView {

    @Mapping("SIZE(kittens)")
    public Integer getKittenSize();
    
}
----

NOTE: An entity view does not have to be an interface, it can be any class.

Moreover you can see that it is possible to use whole expressions inside the `@Mapping` annotations.
The allowed expression will be covered in more detail in subsequent chapters.

Another useful feature are subviews which is illustrated in following example.

[source,java]
----
@EntityView(Landlord.class)
public interface LandlordView {

    @IdMapping
    public Long getId();

    public String getName();
    
    public Integer getAge();
    
    @Mapping("ownedProperties")
    public PropertyAddressView getHouses();
    
}

@EntityView(Property.class)
public interface PropertyAddressView {

    @IdMapping
    public Long getId();

    public String getAddress();
    
}
----

The last feature we are going to cover here are filters and sorters in conjunction with `EntityViewSetting` which
allows the dynamic configuration of filters and sorters on your entity view and are
also usable together with pagination. This makes them ideal an ideal fit whenever you need to query data for display
in a filterable and/or sortable data table. Following example illustrates how this looks like:

[source,java]
----
@EntityView(Cat.class)
@ViewFilters({
    @ViewFilter(name = "customFilter", value = FilteredDocument.CustomFilter.class)
})
public interface FilteredCatView {

    @AttributeFilter(ContainsFilter.class)
    public String getName();

    public static class CustomFilter extends ViewFilterProvider {
        @Override
        public <T extends WhereBuilder<T>> T apply(T whereBuilder) {
            return whereBuilder.where("doctor.name").like().expression("Julia%").noEscape();
        }
    }
}
----

In this example we once again define a view on our Cat entity and select the cat's name only.
But in addition we applied a filter on the name attribute. In this case we chose the `ContainsFilter`, one
of the predefined filters. We also defined a custom filter where we check whether the cat's doctor's name
starts with the string 'Julia'.
The next code snippet shows how we dynamically set the actual filter value by which the
query should filter and how we paginate the resulting query.

[source,java]
----
// Base setting
EntityViewSetting<FilteredCatView, PaginatedCriteriaBuilder<FilteredCatView>> setting = 
        EntityViewSetting.create(FilteredCatView.class, 0, 10);

// Query
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class);
setting.addAttributeFilter("name", "Kitty");

PaginatedCriteriaBuilder<FilteredCatView> paginatedCb = evm.applySetting(setting, cb);
PagedList<FilteredCatView> result = paginatedCb.getResultList();
----

[[getting-started-summary]]
=== Summary

If you want to go into more detail, you are now ready to discover the other chapters of the documentation or
the API yourself.
