[[spring-data-integration]]
== Spring Data integration

Apart from a plain Spring integration which is handy for configuring and providing an `EntityViewManager` for injection,
there is also a Spring Data integration module which tries to make using entity views with Spring Data as convenient as using entities.

=== Setup

To setup the project for Spring Data you have to add dependencies as described in the <<setup>> section
and make a beans available for `CriteriaBuilderFactory` and `EntityViewManager` instances as laid out in the <<anchor-environment-spring,Spring environment>> section.

When enabling JPA repositories, make sure you configure `EntityViewRepositoryFactoryBean` as _repositoryFactoryBeanClass_.
Optionally specify a custom basePackage for repository class scanning and a custom entityManagerFactoryRef.

[source,java]
----
@EnableJpaRepositories(repositoryFactoryBeanClass = EntityViewRepositoryFactoryBean.class)
----

=== Features

The integration comes with a convenience base interface `com.blazebit.persistence.impl.springdata.repository.EntityViewRepository`
that you can use for your repository definitions.

Assume we have the following entity view:

[source,java]
----
@EntityView(Cat.class)
public interface SimpleCatView {

    @IdMapping("id")
    public getId();

    String getName();

    @Mapping("LOWER(name)")
    String getLowerCaseName();

    Integer getAge();
}
----

A very simple repository might look like this:

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends EntityViewRepository<SimpleCatView, Long> {

    List<SimpleCatView> findByLowerCaseName(String lowerCaseName);
}
----

Since we use EntityViewRepository as a base interface we inherit the most commonly used repository methods.
You can now use this repository as any other Spring Data repository:

[source,java]
----
@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay() {
        return simpleCatViewRepository.findAll();
    }

    public SimpleCatView findCatByName(String name) {
        return simpleCatViewRepository.findByLowerCaseName(name.toLowerCase());
    }
}
----

All other Spring Data repository features like restrictions, pagination, slices and ordering are supported as usual.
Please consult the Spring Data documentation for further information.