[[spring-data-integration]]
== Spring Data integration

Apart from a plain Spring integration which is handy for configuring and providing an `EntityViewManager` for injection,
there is also a Spring Data integration module which tries to make using entity views with Spring Data as convenient as using entities.

[[spring-data-setup]]
=== Setup

To setup the project for Spring Data you have to add dependencies as described in the <<getting-started-setup>> section
and make beans available for `CriteriaBuilderFactory` and `EntityViewManager` instances as laid out in the <<anchor-environment-spring,Spring environment>> section.

In short, the following Maven dependencies are required

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-2.0</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-hibernate-5.2</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

If you still work with Spring Data 1.x you will have to use a different integration as Spring Data 2.x changed quite a bit.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-1.x</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

The dependencies for other JPA providers or other versions can be found in the link:{core_doc}#maven-setup[core module setup section].

A possible bean configuration for the required beans `CriteriaBuilderFactory` and `EntityViewManager` in short might look like this.

[source,java]
----
@Configuration
public class BlazePersistenceConfiguration {

    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    public CriteriaBuilderFactory createCriteriaBuilderFactory() {
        CriteriaBuilderConfiguration config = Criteria.getDefault();
        // do some configuration
        return config.createCriteriaBuilderFactory(entityManagerFactory);
    }
}
----

[source, java]
----
@Configuration
public class BlazePersistenceConfiguration {

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    // inject the criteria builder factory which will be used along with the entity view manager
    public EntityViewManager createEntityViewManager(CriteriaBuilderFactory cbf, EntityViewConfiguration entityViewConfiguration) {
        return entityViewConfiguration.createEntityViewManager(cbf);
    }
}
----

When enabling JPA repositories, make sure you configure `BlazePersistenceRepositoryFactoryBean` as _repositoryFactoryBeanClass_.
Optionally specify a custom basePackage for repository class scanning and a custom entityManagerFactoryRef.

[source,java]
----
@EnableJpaRepositories(repositoryFactoryBeanClass = BlazePersistenceRepositoryFactoryBean.class)
----

[[spring-data-features]]
=== Features

The integration comes with a convenience base interface `com.blazebit.persistence.spring.data.repository.EntityViewRepository`
that you can use for your repository definitions.

Assume we have the following entity view:

[source,java]
----
@EntityView(Cat.class)
public interface SimpleCatView {

    @IdMapping
    public getId();

    String getName();

    @Mapping("LOWER(name)")
    String getLowerCaseName();

    Integer getAge();
}
----

A very simple repository might look like this:

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends EntityViewRepository<SimpleCatView, Long> {

    List<SimpleCatView> findByLowerCaseName(String lowerCaseName);
}
----

Since we use EntityViewRepository as a base interface we inherit the most commonly used repository methods.
You can now use this repository as any other Spring Data repository:

[source,java]
----
@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay() {
        return simpleCatViewRepository.findAll();
    }

    public SimpleCatView findCatByName(String name) {
        return simpleCatViewRepository.findByLowerCaseName(name.toLowerCase());
    }
}
----

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#specifications[Spring Data Specifications] can be used without restrictions. There is also the convenience base interface `com.blazebit.persistence.spring.data.repository.EntityViewSpecificationExecutor` that can be extended from.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends EntityViewRepository<SimpleCatView, Long>, EntityViewSpecificationExecutor<SimpleCatView, Cat> {
}

@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay(final int minAge) {
        return simpleCatViewRepository.findAll(new Specification<Cat>() {
            @Override
            public Predicate toPredicate(Root<Cat> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder criteriaBuilder) {
                return criteriaBuilder.ge(root.<Integer>get("age"), minAge);
            }
        });
    }
----

The integration handles ad-hoc uses of https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.entity-graph[`@EntityGraph`] by adapting the query generation through call of link:{core_jdoc}/persistence/CriteriaBuilder.html#fetch(java.lang.String...)[`CriteriaBuilder.fetch()`] rather than passing the entity graphs as hints.

Another notable feature the integration provides is the support for the return type `KeysetAwarePage` as a replacement for `Page`.
By using `KeysetAwarePage` the keyset pagination feature is enabled for the repository method.

[source,java]
----
@Transactional(readOnly = true)
public interface KeysetAwareCatViewRepository extends Repository<Cat, Long> {

    KeysetAwarePage<SimpleCatView> findAll(Pageable pageable);
}
----

Note that the `Pageable` should be an instance of `KeysetPageable` if keyset pagination should be used. A `KeysetPageable` can be retrieved through the `KeysetAwarePage` or manually
by constructing a `KeysetPageRequest`. Note that constructing a `KeysetPageRequest` or actually the contained `KeysetPage` manually is not recommended. When working with Spring MVC,
the Spring Data Rest integration might come in handy. For stateful server side frameworks, it's best to put the `KeysetAwarePage` into a session like storage
to be able to use the `previousOrFirst()` and `next()` methods for retrieving `KeysetPageable` objects.

When using parameters in an entity view, these parameters are usually passed in as optional parameters to an `EntityViewSetting` rather than normal query parameters.
You can customize the `EntityViewSetting` object that is used by providing a `EntityViewSettingProcessor` like so.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends Repository<Cat, Long> {
    List<SimpleCatView> findAll(EntityViewSettingProcessor<SimpleCatView> processor);
}
----

[source,java]
----
simpleCatViewRepository.findAll(setting -> setting.withOptionalParameter("language", Locale.US));
----

To just pass optional parameters, one can also annotate a parameter with `@OptionalParam` to designate it as being an optional parameter and to be included in the generated `EntityViewSetting`.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends Repository<Cat, Long> {
    List<SimpleCatView> findAll(@OptionalParam("language") Locale language);
}
----

All other Spring Data repository features like restrictions, pagination, slices and ordering are supported as usual.
Please consult the Spring Data documentation for further information.

=== Spring Data Rest integration

The Spring Data Rest integration offers similar pagination features for keyset pagination to what Spring Data already offers for normal pagination.
First, a keyset pagination enabled repository is needed.


[source,java]
----
@Transactional(readOnly = true)
public interface KeysetAwareCatViewRepository extends Repository<Cat, Long> {

    KeysetAwarePage<SimpleCatView> findAll(Pageable pageable);
}
----

A controller can then use this repository like the following:

[source,java]
----
@Controller
public class MyCatController {

    @Autowired
    private KeysetAwareCatViewRepository simpleCatViewRepository;

    @RequestMapping(path = "/cats", method = RequestMethod.GET)
    public Page<SimpleCatView> getCats(@KeysetConfig(Cat.class) KeysetPageable pageable) {
        return simpleCatViewRepository.findAll(pageable);
    }
----

Note that {projectname} imposes some very important requirements that have to be fulfilled

* There must always be a sort specification
* The last sort specification must be a unique identifier

For the keyset pagination to kick in, the client has to _remember_ the values by which the sorting is done of the first and the last element of the result.
The values then need to be passed to the next request as JSON encoded query parameters. The values of the first element should use the parameter `lowest` and the last element the parameter `highest`.

The following will illustrate how this works.

First, the client makes an initial request.

[source]
----
GET /cats?page=0&size=3&sort=id,desc
{
    content: [
        { id: 10, name: 'Felix', age: 10 },
        { id: 9, name: 'Robin', age: 4 },
        { id: 8, name: 'Billy', age: 7 }
    ]
}
----

It's the responsibility of the client to remember the attributes by which it sorts of the first and last element.
In this case, `{id: 10}` will be remembered as `lowest` and `{id: 8}` as `highest`. The client also has to remember the page/offset and size which was used to request this data.
When the client then wants to switch to the next page/offset, it has to pass `lowest` and `highest` as parameters as well as `prevPage`/`prevOffset` representing the page/offset that was used before.

Note that the following is just an example for illustration. Stringified JSON objects in JavaScript should be encoded view `encodeURI()` before being used as query parameter.

[source]
----
GET /cats?page=1&size=3&sort=id,desc&prevPage=0&lowest={id:10}&highest={id:8}
{
    content: [
        { id: 7, name: 'Kitty', age: 1 },
        { id: 6, name: 'Bob', age: 8 },
        { id: 5, name: 'Frank', age: 14 }
    ]
}
----

This will make use of keyset pagination as can be seen by looking at the generated JPQL or SQL query.

Note that the client should _drop_ or _forget_ the `lowest`, `highest` and `prevPage`/`prevOffset` values when

* the page size changes and it is expected to show data not connected to the last page
* the sorting changes
* the filtering changes

For a full AngularJS example see the following https://github.com/Blazebit/blaze-persistence/blob/master/examples/spring-data-rest/src/main/resources/static/app.js[example project].