[[entity-view-basic-user-type-spi]]
== BasicUserType SPI

Just like JPA providers offer an SPI to make use of custom types for basic values, {projectname} also does.
For read models, the type isn't very important as the JPA provider handles the construction of the values and only provides entity views with object instance.
Since write models need to handle change detection and mutability aspects of basic types i.e. non-subview type, the `BasicUserType` interface SPI is needed.

=== Supported types

There are several well known types registered out of the box.
// NOTE: Keep in sync with MutableBasicUserTypeRegistry

* `boolean`, `java.lang.Boolean`
* `char`, `java.lang.Character`
* `byte`, `java.lang.Byte`
* `short`, `java.lang.Short`
* `int`, `java.lang.Integer`
* `long`, `java.lang.Long`
* `float`, `java.lang.Float`
* `double`, `java.lang.Double`
* `java.lang.String`
* `java.math.BigInteger`, `java.math.BigDecimal`
* `java.util.Date`, `java.sql.Time`, `java.sql.Date`, `java.sql.Timestamp`
* `java.util.Calendar`, `java.util.GregorianCalendar`
* `java.util.TimeZone`, `java.lang.Class`
* `java.util.UUID`, `java.net.URL`
* `java.util.Locale`,  `java.util.Currency`
* `byte[]`, `java.lang.Byte[]`
* `char[]`, `java.lang.Character[]`
* `java.io.InputStream`, `java.sql.Blob`
* `java.sql.Clob`, `java.sql.NClob`

If found on the classpath, types for the following classes are registered

* `java.time.LocalDate`, `java.time.LocalDateTime`, `java.time.LocalTime`
* `java.time.OffsetTime`, `java.time.OffsetDateTime`, `java.time.ZonedDateTime`
* `java.time.Duration`, `java.time.Instant`
* `java.time.MonthDay`, `java.time.Year`, `java.time.YearMonth`, `java.time.Period`
* `java.time.ZoneId`, `java.time.ZoneOffset`

If you miss a type you can register it via link:{entity_view_jdoc}/persistence/view/spi/EntityViewConfiguration.html#registerBasicUserType(java.lang.Class,com.blazebit.persistence.view.spi.type.BasicUserType)[`EntityViewConfiguration.registerBasicUserType(Class type, BasicUserType userType)`].

=== Type support for MULTISET fetching

One of the reasons why a custom basic user type might be desirable is the support for `MULTISET` fetching.
When an entity view attribute defines `MULTISET` fetching, the basic user types of all types connected through that attribute must support `MULTISET` fetching.
Normally this is not a problem, because well known user types are fully supported. Using embeddable types, custom composite types or JPA converted types in entity views
is problematic though, because there is no way {projectname} can figure out how to decompose the attribute to a string representation or construct the type from a string representation.
This is where a custom basic user type implementation is desirable.

Depending on whether the type is mutable or not, you can extend the `com.blazebit.persistence.view.spi.type.AbstractMutableBasicUserType` or `com.blazebit.persistence.view.spi.type.ImmutableBasicUserType`.
An example implementation for an embeddable type composed of 2 attributes might look like the following:

[source,java]
----
public class QuantityBasicUserType extends com.blazebit.persistence.view.spi.type.AbstractMutableBasicUserType<Quantity> {

    @Override
    public Quantity deepClone(Quantity object) {
        // Clone the object if it is mutable. For immutable types,
        // you can extend com.blazebit.persistence.view.spi.type.ImmutableBasicUserType and don't need this method
        return object == null ? null : new Quantity(object);
    }

    @Override
    public String toStringExpression(String expression) {
        // A JPQL expression that produces a string format which is then parsed
        return "CONCAT(" + expression + ".value, '/', " + expression + ".unit)";
    }

    @Override
    public Quantity fromString(CharSequence sequence) {
        // The CharSequence has the format as defined through toStringExpression
        // Now it must be de-serialized to a Quantity
        String s = sequence.toString();
        String[] parts = s.split("\\/");
        return new Quantity(new BigDecimal(parts[0]), parts[1]);
    }
}
----

Note that the `deepClone` method is only relevant for mutable types. Don't forget to register the basic user type via link:{entity_view_jdoc}/persistence/view/spi/EntityViewConfiguration.html#registerBasicUserType(java.lang.Class,com.blazebit.persistence.view.spi.type.BasicUserType)[`EntityViewConfiguration.registerBasicUserType(Class type, BasicUserType userType)`].

[source,java]
----
EntityViewConfiguration configuration = ...
configuration.registerBasicUserType(Quantity.class, new QuantityBasicUserType());
----

=== Type support for write models

When a basic type is used in a write model, it is very important that an appropriate `BasicUserType` is registered.
If no basic user type is registered for a type, by default the `com.blazebit.persistence.view.spi.type.MutableBasicUserType` is used.
This basic user type assume the type is mutable which will cause values of that type to always be assumed being dirty.
Updatable entity views containing values of such a type are thus always considered being dirty which has the effect, that every call to
link:{entity_view_jdoc}/persistence/view/EntityViewManager.html#save(javax.persistence.EntityManager,%20java.lang.Object)[`EntityViewManager.save(EntityManager em, Object view)`]
will cause a flush of attributes containing that value.
The <<Change Model API,updatable-entity-view-change-model-api>> is also affected of this by always reporting such attributes as being dirty.

Immutable types, like e.g. `java.lang.String` already does, can use the basic user type implementation `com.blazebit.persistence.view.spi.type.ImmutableBasicUserType`
which assumes objects of the type are immutable.

A proper basic user type implementation for mutable types, when based on the provided type `com.blazebit.persistence.view.spi.type.AbstractMutableBasicUserType`
only needs an implementation for cloning a value. The cloned value is used to e.g. keep the initial state so that later changes can be detected by checking equality.

=== Type support for JPA managed types

JPA managed types are also considered mutable by default, and since no dirty tracking information is available by default, objects of that such types are always considered dirty thus also always flushed.
An integration with the native dirty tracking mechanism of the JPA provider might improve performance and will be considered in future versions.
Entity types that handle change tracking manually, can implement a custom basic user type to improve the performance for usages of that entity type within updatable entity views,
but are generally recommended to switch to subviews instead.

For further information on the possible SPI methods consult the JavaDoc of the link:{entity_view_jdoc}/persistence/view/spi/type/BasicUserType.html[`BasicUserType` interface]

=== Optimistic locking version type support

To allow an attribute to be used as version for optimistic locking, the registered basic type also needs to implement the `com.blazebit.persistence.view.spi.type.VersionBasicUserType` interface.
This type additionally requires to provide an implementation for returning the _next version_ based on a given current version.