== Configuration

{projectname} can be configured by setting properties on a `com.blazebit.persistence.view.spi.EntityViewConfiguration` object and creating a `EntityViewManager` from it.

[[anchor-configuration-properties]]
=== Configuration properties

[[PROXY_EAGER_LOADING]]
==== PROXY_EAGER_LOADING

Defines whether proxy classes for entity views should be created eagerly when creating the `EntityViewManager` or on demand.
To improve startup performance this is deactivated by default. When using entity views in a clustered environment you might want to enable this!

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.proxy.eager_loading 
| Type | boolean 
| Default | false
| Applicable | Configuration only
|====================

[[TEMPLATE_EAGER_LOADING]]
==== TEMPLATE_EAGER_LOADING

Defines whether entity view template objects should be created eagerly when creating the `EntityViewManager` or on demand.
To improve startup performance this is deactivated by default. In a production environment you might want to enable this so that templates don't have to be built on-demand but are retrieved from a cache.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.eager_loading 
| Type | boolean 
| Default | false
| Applicable | Configuration only
|====================

[[PROXY_UNSAFE_ALLOWED]]
==== PROXY_UNSAFE_ALLOWED

Defines whether proxy classes that support using the getter methods in a constructor should be allowed.
These proxy classes have to be defined via `sun.misc.Unsafe` to avoid class verification errors.
Disabling this property makes the use of the getter in the constructor return the default value for the property instead of the actual value.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.proxy.unsafe_allowed
| Type | boolean 
| Default | true
| Applicable | Configuration only
|====================

[[EXPRESSION_VALIDATION_DISABLED]]
==== EXPRESSION_VALIDATION_DISABLED

Defines whether the expressions of entity view mappings should be validated.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.expression_validation_disabled
| Type | boolean 
| Default | true
| Applicable | Configuration only
|====================

[[DEFAULT_BATCH_SIZE]]
==== DEFAULT_BATCH_SIZE

Defines the default batch size to be used for attributes that are fetched via the `SELECT` fetch strategy.
To specify the batch size of a specific attribute, append the attribute name after the "batch_size" like
e.g. `com.blazebit.persistence.view.batch_size.subProperty`

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.batch_size
| Type | int 
| Default | 1
| Applicable | Always
|====================

[[EXPECT_BATCH_CORRELATION_VALUES]]
==== EXPECT_BATCH_CORRELATION_VALUES

WARNING: This was deprecated in favor of `EXPECT_BATCH_MODE`.

Defines whether by default batching of correlation values or view root ids is expected for attributes that are fetched via the `SELECT` fetch strategy.
To specify the batch expectation of a specific attribute, append the attribute name after the "batch_correlation_values" like
e.g. `com.blazebit.persistence.view.batch_correlation_values.subProperty`

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.batch_correlation_values
| Type | boolean
| Default | true
| Applicable | Always
|====================

[[EXPECT_BATCH_MODE]]
==== EXPECT_BATCH_MODE

Defines the expected batch mode i.e. whether correlation values, view root ids or embedding view ids are expected to be batched for attributes that are fetched via the `SELECT` fetch strategy.
To specify the batch expectation of a specific attribute, append the attribute name after the "batch_mode" like
e.g. `com.blazebit.persistence.view.batch_mode.subProperty`

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.batch_mode
| Type | String
| Default | values, view_roots, embedding_views
| Applicable | Always
|====================

[[UPDATER_EAGER_LOADING]]
==== UPDATER_EAGER_LOADING

Defines whether entity view updater objects should be created eagerly when creating the `EntityViewManager` or on demand.
To improve startup performance this is deactivated by default. In a production environment you might want to enable this so that updaters don't have to be built on-demand but are retrieved from a cache.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.eager_loading
| Type | boolean
| Default | false
| Applicable | Configuration only
|====================

[[UPDATER_FLUSH_MODE]]
==== UPDATER_FLUSH_MODE

Defines the flush mode the entity view updater objects should be using which is normally defined via `@UpdatableEntityView(mode = ...)`.
This is a global override. To override the flush mode of a specific class, append the fully qualified class name after the "flush_mode" part like
e.g. `com.blazebit.persistence.view.updater.flush_mode.com.test.MyUpdatableCatView`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.flush_mode
| Type | String
| Values | partial, lazy or full
| Default | none
| Applicable | Configuration only
|====================

[[UPDATER_FLUSH_STRATEGY]]
==== UPDATER_FLUSH_STRATEGY

Defines the flush strategy the entity view updater objects should be using which is normally defined via `@UpdatableEntityView(strategy = ...)`.
This is a global override. To override the flush strategy of a specific class, append the fully qualified class name after the "flush_strategy" part like
e.g. `com.blazebit.persistence.view.updater.flush_strategy.com.test.MyUpdatableCatView`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.flush_strategy
| Type | String
| Values | entity or query
| Default | none
| Applicable | Configuration only
|====================

[[UPDATER_DISALLOW_OWNED_UPDATABLE_SUBVIEW]]
==== UPDATER_DISALLOW_OWNED_UPDATABLE_SUBVIEW

Defines whether the use of an updatable entity view type for owned relationships is disallowed.
By default the use is disallowed i.e. the default value is `true`, but since there might be strange models out there, it is possible to allow this.

The main reason to disallow this, is that this kind of usage would break the idea of a separate model per use case, but there is also technical reason.
Updatable entity views are only allowed to have a single _parent_ object due to the way dirty tracking is implemented. This is not necessarily a limitation,
but was simply done this way because the developers believe in the model per use case approach and want to encourage this way of working.

During loading of entity views, tuples are transformed into entity views. Updatable entity views are de-duplicated i.e. if another tuple would be transformed,
it uses the existing object instead. During construction of an entity view all it's child views are registered for dirty tracking.
Since an updatable view may only have one parent, and owned *ToOne relationships do not guarantee that the relationship object will only have one parent,
this will result in a runtime exception depending on the data.

Beware that allowing updatable entity view types for *ToOne relationships might lead to these exceptions at runtime if the relationship isn't logically a OneToOne.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.disallow_owned_updatable_subview
| Type | boolean
| Default | true
| Applicable | Configuration only
|====================

[[UPDATER_STRICT_CASCADING_CHECK]]
==== UPDATER_STRICT_CASCADING_CHECK

Defines whether the strict cascading check that disallows setting updatable or creatable entity views on non-cascading attributes
before being associated with a cascading attribute is enabled.
When disabled, it is possible, like in JPA, that the changes done to an updatable entity view are not flushed when it is not associated with an attribute that cascades updates.
By default the use is enabled i.e. the default value is `true`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.strict_cascading_check
| Type | boolean
| Default | true
| Applicable | Configuration only
|====================

[[UPDATER_ERROR_ON_INVALID_PLURAL_SETTER]]
==== UPDATER_ERROR_ON_INVALID_PLURAL_SETTER

Defines whether warnings or boot time validation errors should be emitted when invalid plural attribute setters are encountered while the strict cascading check is enabled.
When `true`, a boot time validation error is thrown when encountering an invalid setter, otherwise just a warning.
This configuration has no effect when the strict cascading check is disabled.
By default the use is disabled i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.updater.error_on_invalid_plural_setter
| Type | boolean
| Default | false
| Applicable | Configuration only
|====================

[[PAGINATION_DISABLE_COUNT_QUERY]]
==== PAGINATION_DISABLE_COUNT_QUERY

Defines whether the pagination count query should be disabled when applying a `EntityViewSetting` to a `CriteriaBuilder`.
When `true`, the pagination count query is disabled via `PaginatedCriteriaBuilder.withCountQuery(false)`.
By default the pagination count query is enabled i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.pagination.disable_count_query
| Type | boolean
| Default | false
| Applicable | EntityViewSetting only
|====================

[[PAGINATION_EXTRACT_ALL_KEYSETS]]
==== PAGINATION_EXTRACT_ALL_KEYSETS

Defines whether the pagination query should extract all keysets rather than just the first and last ones.
When `true`, the keyset extraction is enabled via `PaginatedCriteriaBuilder.withExtractAllKeysets(true)`.
By default only the first and last keysets are extracted i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.pagination.extract_all_keysets
| Type | boolean
| Default | false
| Applicable | EntityViewSetting only
|====================

[[PAGINATION_FORCE_USE_KEYSET]]
==== PAGINATION_FORCE_USE_KEYSET

Defines whether the pagination query should force the usage of a keyset when available even if page or page size changes.
By default only the first and last keysets are extracted i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.pagination.force_use_keyset
| Type | boolean
| Default | false
| Applicable | EntityViewSetting only
|====================

[[PAGINATION_HIGHEST_KEYSET_OFFSET]]
==== PAGINATION_HIGHEST_KEYSET_OFFSET

Defines the offset from the `maxResults` at which to find the highest keyset i.e. the highest keyset will be at position `Math.min(size, maxResults - offset)`.
Setting 1 along with a maxResults + 1 allows to look ahead one element to check if there are more elements which is useful for pagination with lazy page count or endless scrolling.
By default the offset is disabled i.e. the default value is `null`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.pagination.highest_keyset_offset
| Type | integer
| Default | null
| Applicable | EntityViewSetting only
|====================
[[PAGINATION_BOUNDED_COUNT]]
==== PAGINATION_BOUNDED_COUNT
Defines the maximum value up to which the count query should count.
By default the bounded count is disabled i.e. all rows are counted.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.pagination.bounded_count
| Type | integer
| Default | null
| Applicable | EntityViewSetting only
|====================

[[STATIC_BUILDER_SCANNING_DISABLED]]
==== STATIC_BUILDER_SCANNING_DISABLED

Defines whether the scanning for `@StaticBuilder` classes for the registered entity views should be disabled.
When `true`, the scanning is disabled which improves startup performance but causes that entity view builders returned via `EntityViewManager.createBuilder()` will use a generic implementation.
By default the scanning is enabled i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.static_builder_scanning_disabled
| Type | boolean
| Default | false
| Applicable | Configuration only
|====================

[[STATIC_IMPLEMENTATION_SCANNING_DISABLED]]
==== STATIC_IMPLEMENTATION_SCANNING_DISABLED

Defines whether the scanning for `@StaticImplementation` classes for the registered entity views should be disabled.
When `true`, the scanning is disabled which improves startup performance but causes that entity view implementations will be generated at runtime.
By default the scanning is enabled i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.static_implementation_scanning_disabled
| Type | boolean
| Default | false
| Applicable | Configuration only
|====================

[[STATIC_METAMODEL_SCANNING_DISABLED]]
==== STATIC_METAMODEL_SCANNING_DISABLED

Defines whether the scanning for `@StaticMetamodel` classes for the registered entity views should be disabled.
When `true`, the scanning is disabled which improves startup performance but causes that the static metamodels are not initialized.
By default the scanning is enabled i.e. the default value is `false`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.static_metamodel_scanning_disabled
| Type | boolean
| Default | false
| Applicable | Configuration only
|====================

[[CREATE_EMPTY_FLAT_VIEWS]]
==== CREATE_EMPTY_FLAT_VIEWS

Defines whether empty flat views should be created by default if not specified via `@EmptyFlatViewCreation`.
When `false`, null will be set for an attribute if the flat view would be empty, otherwise an empty flat view is set.
By default the creation of empty flat views is enabled i.e. the default value is `true`.

[width="100%",cols="2,10",options="header,footer"]
|====================
| Key | com.blazebit.persistence.view.create_empty_flat_views
| Type | boolean
| Default | true
| Applicable | Configuration only
|====================