[[graphql-integration]]
== GraphQL integration

GraphQL is a language for data communication that requires a schema. Defining that schema and keeping it in sync with the model can become a very painful task.
This is where the GraphQL integration comes to rescue as it is capable of contributing entity view types to the GraphQL schema
and also create a `EntityViewSetting` object from a GraphQL `DataFetchingEnvironment` with full support for partial loading as defined by selection lists.

In addition, it also has support for the Relay pagination specification to allow easy keyset pagination.

[[graphql-setup]]
=== Setup

To use the GraphQL integration you need the following Maven dependencies:

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

or if you are using Jakarta JPA

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql-jakarta</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

Note that the integration works with the de facto standard runtime for GraphQL which is `graphql-java`. At least version 17.3 is required.

=== Usage

The integration works by contributing entity view type as GraphQL types to a GraphQL `TypeDefinitionRegistry` or `GraphQLSchema.Builder`.

Let's consider the following entity views

[source,java]
----
@EntityView(Person.class)
public interface PersonIdView {
    @IdMapping
    Long getId();
}
@EntityView(Person.class)
public interface PersonSimpleView extends PersonIdView {
    String getName();
}
@EntityView(Cat.class)
public interface CatSimpleView {
    @IdMapping
    Long getId();
    String getName();
}
@EntityView(Cat.class)
public interface CatWithOwnerView extends CatSimpleView {
    PersonSimpleView getOwner();
}
----

This will generate the following GraphQL types

[source,graphql]
----
type CatSimpleView {
  id: ID!
  name: String
}
type CatWithOwnerView {
  id: ID!
  name: String
  owner: PersonSimpleView
}
type PersonIdView {
  id: ID!
}
type PersonSimpleView {
  id: ID!
  name: String
}
----

The integration happens through the class `GraphQLEntityViewSupportFactory`, which produces a `GraphQLEntityViewSupport` which you can then use.
The created `GraphQLEntityViewSupport` object is a singleton that should only be created during boot
and can be used for creating `EntityViewSetting` objects in GraphQL `DataFetcher` implementations.
Usually, the object is exposed as `@Bean` in Spring or `@ApplicationScoped` bean in CDI.

The `GraphQLEntityViewSupport.createSetting()` and `GraphQLEntityViewSupport.createPaginatedSetting()` methods inspect the data fetching environment and know which entity view type is needed,
but you can also provide a custom `EntityViewSetting` with a custom entity view type or some prepared filters/sorters.
In addition, these methods will determine what to fetch according to the `DataFetchingEnvironment.getSelectionList()`.
This will lead to the optimal query to be generated for the fields that are requested. This is not only about skipping select items, but also about avoiding unnecessary joins!

==== Plain graphql-java setup

With just graphql-java, you have to provide a schema and do the runtime-wiring. This could look like the following with a sample schema:

[source,graphql]
----
type Query {
    catById(id: ID!): CatWithOwnerView
}
----

and the setup logic:

[source,java]
----
EntityViewManager evm = ...

// Read in the GraphQL schema
URL url = Resources.getResource("schema.graphqls");
String sdl = Resources.toString(url, StandardCharsets.UTF_8);
TypeDefinitionRegistry typeRegistry = new SchemaParser().parse(sdl);

// Configure how to integrate entity views
boolean defineNormalTypes = true;
boolean defineRelayTypes = true;
GraphQLEntityViewSupportFactory graphQLEntityViewSupportFactory = new GraphQLEntityViewSupportFactory(defineNormalTypes, defineRelayTypes);
graphQLEntityViewSupportFactory.setImplementRelayNode(false);
graphQLEntityViewSupportFactory.setDefineRelayNodeIfNotExist(true);

// Integrate and create the support class for extraction of EntityViewSetting objects
GraphQLEntityViewSupport graphQLEntityViewSupport = graphQLEntityViewSupportFactory.create(typeRegistry, evm);
----

Next, one needs to define a `DataFetcher` for the defined query `catById` like so

[source,java]
----
CatViewRepository repository;

RuntimeWiring.newRuntimeWiring()
    .type(TypeRuntimeWiring.newTypeWiring("Query")
            .dataFetcher("catById", new DataFetcher() {
                @Override
                public Object get(DataFetchingEnvironment dataFetchingEnvironment) {
                    return repository.findById(
                            graphQLEntityViewSupport.createSetting(dataFetchingEnvironment),
                            Long.valueOf(dataFetchingEnvironment.getArgument("id"))
                    );
                }
            })
    )
    .build();
----

Finally, the `RuntimeWiring` and `TypeDefinitionRegistry` are joined together to a `GraphQL` schema which is required for the GraphQL runtime.

[source,java]
----
SchemaGenerator schemaGenerator = new SchemaGenerator();
return schemaGenerator.makeExecutableSchema(typeRegistry, runtimeWiring);
----

===== Naming types or additional fields

Types can be explicitly named by putting the `@GraphQLName` annotation on a type.

[source,java]
----
@GraphQLName("TheEntity")
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...
}
----

Additional fields can be declared as getter methods that follow the Java beans convention:

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    default String getAdditionalField() {
        return "some data";
    }

    @GraphQLName("additionalData")
    default String getData() {
        return "more data";
    }
}
----

In this case the schema for `MyEntityView` will contain two additional fields `additionalField` and `additionalData`.
Note that when the GraphQL field name does not match the property name of a getter method like in the previous example,
an additional data fetcher must be declared for the field:

[source,java]
----
RuntimeWiring.newRuntimeWiring()
    .type(TypeRuntimeWiring.newTypeWiring("MyEntityView")
            .dataFetcher("additionalData", new DataFetcher() {
                @Override
                public Object get(DataFetchingEnvironment dataFetchingEnvironment) {
                      Object source = dataFetchingEnvironment.getSource();
                      if (source instanceof MyEntityView) {
                          return ((MyEntityView) source).getData();
                      }
                      return null;
                }
            })
    )
    .build();
----

===== Ignoring types or fields

Types can be explicitly ignored by putting the `@GraphQLIgnore` annotation on a type.

It's also possible to prevent getters in entity views to appear as fields in the GraphQL type schema, by annotating the getter method with the `@GraphQLIgnore` annotation.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLIgnore
    default String getAdditionalField() {
        return "some data";
    }
}
----

===== Forcing non-null types on fields

The type of a GraphQL field can be forced to be non-null by putting the `@GraphQLNonNull` annotation on a getter method.

Usually, the integration is able to figure out non-null types through its nullability analysis of mapping expressions,
but for custom methods or cases when the analysis fails, the explicit annotation can be used.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLNonNull
    default String getAdditionalField() {
        return "some data";
    }
}
----

For a full example see the following https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-graphql/[example project].

==== Netflix DGS setup

To use the Netflix DGS integration you need the following Maven dependencies:

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql-dgs</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

or if you are using Jakarta APIs

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql-dgs-7.0</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

The Netflix DGS setup is similar to the plain graphql-java one, as you have to provide a schema as well, although you have to follow a convention.
A schema must be located in a `schema` folder and have a suffix of `*.graphls` according to the https://netflix.github.io/dgs/configuration/[documentation].
The runtime-wiring looks different though as it supports an annotation based model.
This could look like the following with a sample schema:

[source,graphql]
----
type Query {
    catById(id: ID!): CatWithOwnerView
}
----

Next, one needs to define a `DataFetcher` for the defined query `catById` like so

[source,java]
----
@DgsComponent
public class CatFetcher {

    @Autowired
    CatViewRepository repository;
    @Autowired
    GraphQLEntityViewSupport graphQLEntityViewSupport;

    @DgsQuery
    public CatWithOwnerView catById(@InputArgument("id") Long id, DataFetchingEnvironment dataFetchingEnvironment) {
        return repository.findById(graphQLEntityViewSupport.createSetting(dataFetchingEnvironment), Long.valueOf(dataFetchingEnvironment.getArgument("id")));
    }
}
----

===== Naming types or additional fields

Types can be explicitly named by putting the `@GraphQLName` annotation on a type.

[source,java]
----
@GraphQLName("TheEntity")
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...
}
----

Additional fields can be declared as getter methods that follow the Java beans convention:

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    default String getAdditionalField() {
        return "some data";
    }

    @GraphQLName("additionalData")
    default String getData() {
        return "more data";
    }
}
----

In this case the schema for `MyEntityView` will contain two additional fields `additionalField` and `additionalData`.
Note that when the GraphQL field name does not match the property name of a getter method like in the previous example,
an additional data fetcher must be declared for the field:

[source,java]
----
@DgsComponent
public class GraphQLExtensionApi {
    @DgsData(parentType = "MyEntityView", field = "theData")
    public String getNodeData(DataFetchingEnvironment dataFetchingEnvironment) {
      Object source = dataFetchingEnvironment.getSource();
      if (source instanceof MyEntityView) {
          return ((MyEntityView) source).getData();
      }
      return null;
    }
}
----

===== Ignoring types or fields

Types can be explicitly ignored by putting the `@GraphQLIgnore` annotation on a type.

It's also possible to prevent getters in entity views to appear as fields in the GraphQL type schema, by annotating the getter method with the `@GraphQLIgnore` annotation.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLIgnore
    default String getAdditionalField() {
        return "some data";
    }
}
----

===== Forcing non-null types on fields

The type of a GraphQL field can be forced to be non-null by putting the `@GraphQLNonNull` annotation on a getter method.

Usually, the integration is able to figure out non-null types through its nullability analysis of mapping expressions,
but for custom methods or cases when the analysis fails, the explicit annotation can be used.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLNonNull
    default String getAdditionalField() {
        return "some data";
    }
}
----

For a full example see the following https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-graphql/[example project].

==== SPQR setup

To use the SPQR GraphQL integration you need the following Maven dependencies:

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql-spqr</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

or if you are using Jakarta JPA

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-graphql-spqr-jakarta</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

The SPQR configuration is very simple and since the framework is fully declarative, you don't need a dedicated GraphQL schema definition.

[source,java]
----
@Configuration
public class GraphQLProvider {

    @Autowired
    EntityViewManager evm;
    @Autowired
    GraphQLSchema graphQLSchema;

    private GraphQLEntityViewSupport graphQLEntityViewSupport;

    @PostConstruct
    public void init() {
        GraphQLEntityViewSupportFactory graphQLEntityViewSupportFactory = new GraphQLEntityViewSupportFactory(false, false);
        graphQLEntityViewSupportFactory.setImplementRelayNode(false);
        graphQLEntityViewSupportFactory.setDefineRelayNodeIfNotExist(false);
        this.graphQLEntityViewSupport = graphQLEntityViewSupportFactory.create(graphQLSchema, evm);
    }

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    public GraphQLEntityViewSupport graphQLEntityViewSupport() {
        return graphQLEntityViewSupport;
    }

}
----

Next, one needs to define a `DataFetcher` for the defined query `catById` like so

[source,java]
----
@Component
@GraphQLApi
public class CatFetcher {

    @Autowired
    CatViewRepository repository;
    @Autowired
    GraphQLEntityViewSupport graphQLEntityViewSupport;

    @GraphQLQuery
    public CatWithOwnerView catById(@GraphQLArgument(name = "id") Long id, @GraphQLEnvironment ResolutionEnvironment env) {
        return repository.findById(graphQLEntityViewSupport.createSetting(env.dataFetchingEnvironment), id);
    }
}
----

===== Naming types or additional fields

Types can be explicitly named by putting the `@GraphQLType` or `@GraphQLName` annotation on a type.

[source,java]
----
@GraphQLType("TheEntity")
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...
}
----

Additional fields can be declared as getter methods that follow the Java beans convention,
or named explicitly by annotating the methods with `@GraphQLQuery`:

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    default String getAdditionalField() {
        return "some data";
    }

    @GraphQLQuery(name = "additionalData")
    default String getData() {
        return "more data";
    }
}
----

In this case the schema for `MyEntityView` will contain two additional fields `additionalField` and `additionalData`.
Note that when the GraphQL field name does not match the property name of a getter method like in the previous example,
the `@GraphQLName` annotation will not work, and the SPQR annotation `@GraphQLQuery` is preferred.

===== Ignoring types or fields

Types can be explicitly ignored by putting the `@GraphQLIgnore` annotation on a type.

It's also possible to prevent getters in entity views to appear as fields in the GraphQL type schema, by annotating the getter method with the `@GraphQLIgnore` annotation.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLIgnore
    default String getAdditionalField() {
        return "some data";
    }
}
----
===== Forcing non-null types on fields

The type of a GraphQL field can be forced to be non-null by putting the `@GraphQLNonNull` annotation on a getter method.

Usually, the integration is able to figure out non-null types through its nullability analysis of mapping expressions,
but for custom methods or cases when the analysis fails, the explicit annotation can be used.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @GraphQLNonNull
    default String getAdditionalField() {
        return "some data";
    }
}
----

For a full example see the following https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-graphql/[example project].

==== MicroProfile GraphQL - SmallRye

MicroProfile GraphQL (version 1.1 at the time of writing) has a completely different approach, as it is completely annotation based.
At the moment, only the SmallRye implementation is supported and unfortunately, not yet within Quarkus.

Let's consider the following sample schema

[source,graphql]
----
type Query {
    catById(id: ID!): CatWithOwnerView
}
----

and the setup logic:

[source,java]
----
@ApplicationScoped
public class GraphQLProducer {

    @Inject
    EntityViewManager evm;

    GraphQLEntityViewSupport graphQLEntityViewSupport;

    void configure(@Observes GraphQLSchema.Builder schemaBuilder) {
        // Option 1: As of SmallRye GraphQL 1.3.1 you can disable the generation of GraphQL types and annotate all entity views with @Type instead
        // boolean defineNormalTypes = false;
        // boolean defineRelayTypes = false;

        // Option 2: Let the integration replace the entity view GraphQL types
        boolean defineNormalTypes = true;
        boolean defineRelayTypes = true;

        // Configure how to integrate entity views
        GraphQLEntityViewSupportFactory graphQLEntityViewSupportFactory = new GraphQLEntityViewSupportFactory(defineNormalTypes, defineRelayTypes);

        graphQLEntityViewSupportFactory.setImplementRelayNode(false);
        graphQLEntityViewSupportFactory.setDefineRelayNodeIfNotExist(true);
        graphQLEntityViewSupportFactory.setScalarTypeMap(GraphQLScalarTypes.getScalarMap());
        // Integrate and create the support class for extraction of EntityViewSetting objects
        this.graphQLEntityViewSupport = graphQLEntityViewSupportFactory.create(schemaBuilder, evm);
    }

    @Produces
    @ApplicationScoped
    GraphQLEntityViewSupport graphQLEntityViewSupport() {
        return graphQLEntityViewSupport;
    }
}
----

Note that you need a `microprofile-config.properties` file in `META-INF` with the config option `smallrye.graphql.events.enabled=true` to enable the events.

Next, one needs to define a `DataFetcher` for the defined query `catById` like so

[source,java]
----
@GraphQLApi
public class CatFetcher {

    @Inject
    CatViewRepository repository;
    @Inject
    Context context;
    @Inject
    GraphQLEntityViewSupport graphQLEntityViewSupport;

    @Query
    public CatWithOwnerView catById(@Input("id") Long id) {
        return repository.findById(graphQLEntityViewSupport.createSetting(context.unwrap(DataFetchingEnvironment.class)), id);
    }
}
----

===== Naming types or additional fields

Types can be explicitly named by putting the `@Name` or `@GraphQLName` annotation on a type.

[source,java]
----
@Name("TheEntity")
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...
}
----

Additional fields can be declared as getter methods that follow the Java beans convention,
or named explicitly by annotating the methods with `@Query`:

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    default String getAdditionalField() {
        return "some data";
    }

    @Query("additionalData")
    default String getData() {
        return "more data";
    }
}
----

In this case the schema for `MyEntityView` will contain two additional fields `additionalField` and `additionalData`.
Note that when the GraphQL field name does not match the property name of a getter method like in the previous example,
the `@GraphQLName` annotation will not work, and the MicroProfile GraphQL annotation `@Query` is preferred.

===== Ignoring types or fields

Types can be explicitly ignored by putting the `@Ignore` or `@GraphQLIgnore` annotation on a type.

It's also possible to prevent getters in entity views to appear as fields in the GraphQL type schema, by annotating the getter method with the `@GraphQLIgnore` annotation.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @Ignore
    default String getAdditionalField() {
        return "some data";
    }
}
----

===== Forcing non-null types on fields

The type of a GraphQL field can be forced to be non-null by putting the `@NonNull` annotation on a getter method.

Usually, the integration is able to figure out non-null types through its nullability analysis of mapping expressions,
but for custom methods or cases when the analysis fails, the explicit annotation can be used.

[source,java]
----
@EntityView(MyEntity.class)
public interface MyEntityView {
    //...

    @NonNull
    default String getAdditionalField() {
        return "some data";
    }
}
----

For a full example see the following https://github.com/Blazebit/blaze-persistence/blob/main/examples/microprofile-graphql/[example project].

==== Sample query

The repository for the previously presented setups could look like this:

[source,java]
----
public class CatViewRepository {

    private final EntityManager em;
    private final CriteriaBuilderFactory cbf;
    private final EntityViewManager evm;

    public CatViewRepository(EntityManager em, CriteriaBuilderFactory cbf, EntityViewManager evm) {
        this.em = em;
        this.cbf = cbf;
        this.evm = evm;
    }

    public <T> T findById(EntityViewSetting<T, CriteriaBuilder<T>> setting, Long id) {
        return evm.find(em, setting, id);
    }
}
----

A sample GraphQL query

[source,graphql]
----
query {
    findCatById(id: 1) {
        id
        name
    }
}
----

will cause a JPQL query similar to the following

[source,sql]
----
SELECT
    c.id,
    c.name
FROM Cat c
WHERE c.id = :param
----

It does not select or join the owner information, although it is specified in the entity view!
This optimization works through applying the selection list of the `DataFetchingEnvironment` via `EntityViewSetting.fetch()`.

=== Pagination support

GraphQL itself does not really define a standard pagination mechanism, so the integration implements part of the https://facebook.github.io/relay/graphql/connections.htm[Relay pagination specification]
in order to provide support for keyset pagination in a more or less common format.

To generate the types that are necessary for using a Relay compatible client, the `GraphQLEntityViewSupportFactory` can be further configured.

[source,java]
----
boolean defineNormalTypes = true;
// This time, also define the relay types i.e. Connection, Edge and Node
boolean defineRelayTypes = true;
GraphQLEntityViewSupportFactory graphQLEntityViewSupportFactory = new GraphQLEntityViewSupportFactory(defineNormalTypes, defineRelayTypes);
// Implementing the Node interface requires a custom type resolver which is out of scope here, so configure to not doing that
graphQLEntityViewSupportFactory.setImplementRelayNode(false);
// If the type registry does not yet define the Node interface, we specify that it should be generated
graphQLEntityViewSupportFactory.setDefineRelayNodeIfNotExist(true);
----

With the entity views defined before, this will generate the following GraphQL types

[source,graphql]
----
type PageInfo {
  startCursor: String
  endCursor: String
}
type CatWithOwnerViewConnection {
  edges: [CatWithOwnerViewEdge]
  pageInfo: PageInfo
}
type CatWithOwnerViewEdge {
  node: CatWithOwnerViewNode!
  cursor: String!
}
type CatWithOwnerViewNode {
  id: ID!
  name: String
  owner: PersonSimpleView
}
type PersonSimpleView {
  id: ID!
  name: String
}
----

To use these type, the static GraphQL Schema needs to be extended. Note that you can skip this for MicroProfile GraphQL.

[source,graphql]
----
type Query {
    findAll(first: Int, last:Int, offset: Int, before: String, after: String): CatWithOwnerViewConnection!
}
----

The Relay specification defines the `first` and `last` arguments to represent the amount of element to fetch.
Using `first` will fetch the next X elements _after_ the given reference point or the start, according to a specific ordering.
Using `last` will fetch the last X elements _before_ the given reference point or the end, according to a specific ordering.

If you can't use keyset pagination, the GraphQL integration also allows to use an `offset` argument, but it is not recommended as offset based pagination has scalability problems.

A data fetcher for using this, could look like the following

[source,java]
----
CatViewRepository repository = ...
DataFetchingEnvironment dataFetchingEnvironment = ...

EntityViewSetting<Object, ?> setting = graphQLEntityViewSupport.createPaginatedSetting(dataFetchingEnvironment);
// The last order by item must be a unique expression for deterministic ordering
setting.addAttributeSorter("id", Sorters.ascending());
if (setting.getMaxResults() == 0) {
    return new GraphQLRelayConnection<>(Collections.emptyList());
}
return new GraphQLRelayConnection<>(repository.findAll(setting));
----

Note that in case of MicroProfile GraphQL, you will have to define the various input arguments in the method signature of the data fetcher:

[source,java]
----
@Query
public GraphQLRelayConnection<CatWithOwnerView> findAll(
        @Name("first") Integer first,
        @Name("last") Integer last,
        @Name("offset") Integer offset,
        @Name("before") String before,
        @Name("after") String after) {
    // ...
}
----

The `GraphQLEntityViewSupport.createPaginatedSetting()` method is capable of reading all necessary information from the `DataFetchingEnvironment` and the schema.
It knows how to process `first`, `last`, `offset`, `before` and `after` arguments as well as integrates with the selection list feature to

* Avoid count queries to determine the overall count
* Avoid fetching non-requested node attributes

If the query does not specify `first` or `last`, the `EntityViewSetting.getMaxResults()` will be `0` which will cause an exception if used for querying.

Finally, the `DataFetcher` must return a `GraphQLRelayConnection` object that wraps a `List` or `PagedList` such that the correct result structure is produced.

A sample GraphQL query

[source,graphql]
----
query {
  findAll(first: 1){
    edges {
      node {
        id
        name
      }
    }
    pageInfo {
      startCursor
      endCursor
    }
  }
}
----

will cause a JPQL query similar to the following

[source,sql]
----
SELECT
    c.id,
    c.name
FROM Cat c
LIMIT 1
----

and provide a result object like the following

[source]
----
query: {
  findAll: {
    edges: [{
      node: {
        id: 1,
        name: "Cat 1"
      }
    }],
    pageInfo: {
      startCursor: "...",
      endCursor: "..."
    }
  }
}
----

You can the use the `endCursor` on the client side as value for the `after` argument to get the next page:

[source,graphql]
----
query {
  findAll(first: 1, after: "..."){
    edges {
      node {
        id
        name
      }
    }
    pageInfo {
      startCursor
      endCursor
    }
  }
}
----

which will cause a JPQL query similar to the following

[source,sql]
----
SELECT
    c.id,
    c.name
FROM Cat c
WHERE c.id > :previousId
LIMIT 1
----

and provide a result object like the following

[source]
----
query: {
  findAll: {
    edges: [{
      node: {
        id: 2,
        name: "Cat 2"
      }
    }],
    pageInfo: {
      startCursor: "...",
      endCursor: "..."
    }
  }
}
----

For a full example see one of the following example projects:

* https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-graphql/[Plain graphql-java]
* https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-dgs/[Netflix DGS]
* https://github.com/Blazebit/blaze-persistence/blob/main/examples/microprofile-graphql/[MicroProfile GraphQL]
* https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-spqr/[SPQR]
