[[quarkus-integration]]
== Quarkus integration

We provide a basic Quarkus extension that allows to use {projectname} core and entity views in a Quarkus application.
As outlined in the <<quarkus-setup,setup section>> you need the following dependency for the integration:

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-quarkus</artifactId>
    <version>${blaze-persistence.version}</version>
</dependency>
----

The use in native images also requires a dependency on the entity view annotation processor that may be extracted into a separate `native` profile:

[source,xml]
----
<profiles>
    <profile>
        <id>native</id>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>blaze-persistence-entity-view-processor</artifactId>
                <version>${project.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </profile>
</profiles>
----

[[quarkus-features]]
=== Features

The extension includes:

* entity view and entity view listener scanning at deployment time while the remainder of the bootstrapping is performed
at runtime

* default CDI producers for the link:{core_jdoc}/persistence/CriteriaBuilderFactory.html[`CriteriaBuilderFactory`]
and link:{entity_view_jdoc}/persistence/view/EntityViewManager.html[`EntityViewManager`] that can be overridden as documented
in the https://quarkus.io/guides/cdi-reference#default_beans[Quarkus user guide]

* support for hot reload