[[spring-data-integration]]
== Spring Data integration

Apart from a plain Spring integration which is handy for configuring and providing an `EntityViewManager` for injection,
there is also a Spring Data integration module which tries to make using entity views with Spring Data as convenient as using entities.

[[spring-data-setup]]
=== Setup

To setup the project for Spring Data you have to add dependencies as described in the <<getting-started-setup>> section
and make beans available for `CriteriaBuilderFactory` and `EntityViewManager` instances as laid out in the <<anchor-environment-spring,Spring environment>> section.

In short, the following Maven dependencies are required

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-2.7</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-hibernate-5.6</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

For Spring-Data version 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0 or 1.x use the `blaze-persistence-integration-spring-data` artifact with the respective suffix `2.6`, `2.5` `2.4`, `2.3`, `2.2`, `2.1`, `2.0`, `1.x`.

If you are using Jakarta APIs and Spring Framework 6+ / Spring Boot 3+, use this

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-3.3</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-hibernate-6.2</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
----

The dependencies for other JPA providers or other versions can be found in the link:{core_doc}#maven-setup[core module setup section].

A possible bean configuration for the required beans `CriteriaBuilderFactory` and `EntityViewManager` in short might look like this.

[source,java]
----
@Configuration
public class BlazePersistenceConfiguration {

    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    public CriteriaBuilderFactory createCriteriaBuilderFactory() {
        CriteriaBuilderConfiguration config = Criteria.getDefault();
        // do some configuration
        return config.createCriteriaBuilderFactory(entityManagerFactory);
    }
}
----

[source, java]
----
@Configuration
public class BlazePersistenceConfiguration {

    @Bean
    @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
    @Lazy(false)
    // inject the criteria builder factory which will be used along with the entity view manager
    public EntityViewManager createEntityViewManager(CriteriaBuilderFactory cbf, EntityViewConfiguration entityViewConfiguration) {
        return entityViewConfiguration.createEntityViewManager(cbf);
    }
}
----

To enabling Blaze JPA repositories, annotate your configuration or application class with `@EnableBlazeRepositories`.
Optionally specify a custom basePackage for repository class scanning and a custom entityManagerFactoryRef.

[source,java]
----
@EnableBlazeRepositories
----

==== Spring Boot Devtools

It is important to note that {projectname} currently does not integrate with Spring Boot Devtools (`org.springframework.boot:spring-boot-devtools`).
Spring Boot Devtools uses a separate `RestartClassloader` to load classes that frequently change to allow for faster application restarts.
You may experience issues with active Spring Boot Devtools when using {projectname} Entity-Views because the entity
classes in the JPA metamodel are loaded by the `RestartClassloader` whereas the entity classes you annotate your entity views
with are loaded by the base application classloader. This can lead to errors at startup time like:

 The entity class '<your-entity>' used for the entity view '<your-entity-view>' could not be found in the persistence unit!

To work around this issue you either need to completely disable Spring Boot Devtools or alternatively, https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload[exclude]
your entity classes from the `RestartClassloader` by adding properties prefixed with `restart.exclude` to your
`META-INF/spring-devtools.properties`.

[[spring-data-features]]
=== Features

The integration comes with a convenience base interface `com.blazebit.persistence.spring.data.repository.EntityViewRepository`
that you can use for your repository definitions.

Assume we have the following entity view:

[source,java]
----
@EntityView(Cat.class)
public interface SimpleCatView {

    @IdMapping
    public getId();

    String getName();

    @Mapping("LOWER(name)")
    String getLowerCaseName();

    Integer getAge();
}
----

A very simple repository might look like this:

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends EntityViewRepository<SimpleCatView, Long> {

    List<SimpleCatView> findByLowerCaseName(String lowerCaseName);
}
----

Since we use EntityViewRepository as a base interface we inherit the most commonly used repository methods.
You can now use this repository as any other Spring Data repository:

[source,java]
----
@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay() {
        return simpleCatViewRepository.findAll();
    }

    public SimpleCatView findCatByName(String name) {
        return simpleCatViewRepository.findByLowerCaseName(name.toLowerCase());
    }
}
----

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#specifications[Spring Data Specifications] can be used without restrictions. There is also the convenience base interface `com.blazebit.persistence.spring.data.repository.EntityViewSpecificationExecutor` that can be extended from.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends EntityViewRepository<SimpleCatView, Long>, EntityViewSpecificationExecutor<SimpleCatView, Cat> {
}

@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay(final int minAge) {
        return simpleCatViewRepository.findAll(new Specification<Cat>() {
            @Override
            public Predicate toPredicate(Root<Cat> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder criteriaBuilder) {
                return criteriaBuilder.ge(root.<Integer>get("age"), minAge);
            }
        });
    }
----

Because Spring Data Specifications work on a JPA criteria builder we provide `BlazeSpecification` as an alternative that
accepts a {projectname} criteria builder but works analogously apart from that.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends Repository<Cat, Long> {

    Iterable<SimpleCatView> findAll(BlazeSpecification specification);
}

@Controller
public class MyCatController {

    @Autowired
    private SimpleCatViewRepository simpleCatViewRepository;

    public Iterable<SimpleCatView> getCatDataForDisplay(final int minAge) {
        return simpleCatViewRepository.findAll(new BlazeSpecification() {
            @Override
            public void applySpecification(String rootAlias, CriteriaBuilder<?> builder) {
                builder.where("age").ge(minAge);
            }
        });
    }
----

The integration handles ad-hoc uses of https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.entity-graph[`@EntityGraph`] by adapting the query generation through call of link:{core_jdoc}/persistence/CriteriaBuilder.html#fetch(java.lang.String...)[`CriteriaBuilder.fetch()`] rather than passing the entity graphs as hints.

Another notable feature the integration provides is the support for the return type `KeysetAwarePage` as a replacement for `Page`.
By using `KeysetAwarePage` the keyset pagination feature is enabled for the repository method.

[source,java]
----
@Transactional(readOnly = true)
public interface KeysetAwareCatViewRepository extends Repository<Cat, Long> {

    KeysetAwarePage<SimpleCatView> findAll(Pageable pageable);
}
----

Note that the `Pageable` should be an instance of `KeysetPageable` if keyset pagination should be used. A `KeysetPageable` can be retrieved through the `KeysetAwarePage` or manually
by constructing a `KeysetPageRequest`. Note that constructing a `KeysetPageRequest` or actually the contained `KeysetPage` manually is not recommended. When working with Spring WebMvc,
the Spring Data WebMvc or WebFlux integrations might come in handy. For stateful server side frameworks, it's best to put the `KeysetAwarePage` into a session like storage
to be able to use the `previousOrFirst()` and `next()` methods for retrieving `KeysetPageable` objects.

When using parameters in an entity view, these parameters are usually passed in as optional parameters to an `EntityViewSetting` rather than normal query parameters.
You can customize the `EntityViewSetting` object that is used by providing a `EntityViewSettingProcessor` like so.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends Repository<Cat, Long> {
    List<SimpleCatView> findAll(EntityViewSettingProcessor<SimpleCatView> processor);
}
----

[source,java]
----
simpleCatViewRepository.findAll(setting -> setting.withOptionalParameter("language", Locale.US));
----

To just pass optional parameters, one can also annotate a parameter with `@OptionalParam` to designate it as being an optional parameter and to be included in the generated `EntityViewSetting`.

[source,java]
----
@Transactional(readOnly = true)
public interface SimpleCatViewRepository extends Repository<Cat, Long> {
    List<SimpleCatView> findAll(@OptionalParam("language") Locale language);
}
----

All other Spring Data repository features like restrictions, pagination, slices and ordering are supported as usual.
Please consult the Spring Data documentation for further information.

=== Spring Data WebMvc integration

The Spring Data WebMvc integration offers similar pagination features for keyset pagination to what Spring Data WebMvc integration already offers for normal offset pagination.

[[spring-data-webmvc-setup]]
==== Setup

To setup the project for Spring Data WebMvc you have to add the following additional dependency.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-webmvc</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

or if you are using Jakarta APIs and Spring 6+

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-webmvc-jakarta</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

==== Usage

First, a keyset pagination enabled repository is needed which can be done by using `KeysetAwarePage` as return type.

[source,java]
----
@Transactional(readOnly = true)
public interface KeysetAwareCatViewRepository extends Repository<Cat, Long> {

    KeysetAwarePage<SimpleCatView> findAll(Pageable pageable);
}
----

A controller can then use this repository like the following:

[source,java]
----
@RestController
public class MyCatController {

    @Autowired
    private KeysetAwareCatViewRepository simpleCatViewRepository;

    @RequestMapping(path = "/cats", method = RequestMethod.GET)
    public Page<SimpleCatView> getCats(@KeysetConfig(Cat.class) KeysetPageable pageable) {
        return simpleCatViewRepository.findAll(pageable);
    }
}
----

Note that {projectname} imposes some very important requirements that have to be fulfilled

* There must always be a sort specification
* The last sort specification must be a unique identifier

For the keyset pagination to kick in, the client has to _remember_ the values by which the sorting is done of the first and the last element of the result.
The values then need to be passed to the next request as JSON encoded query parameters. The values of the first element should use the parameter `lowest` and the last element the parameter `highest`.

The following will illustrate how this works.

First, the client makes an initial request.

[source]
----
GET /cats?page=0&size=3&sort=id,desc
{
    content: [
        { id: 10, name: 'Felix', age: 10 },
        { id: 9, name: 'Robin', age: 4 },
        { id: 8, name: 'Billy', age: 7 }
    ]
}
----

It's the responsibility of the client to remember the attributes by which it sorts of the first and last element.
In this case, `{id: 10}` will be remembered as `lowest` and `{id: 8}` as `highest`. The client also has to remember the page/offset and size which was used to request this data.
When the client then wants to switch to the next page/offset, it has to pass `lowest` and `highest` as parameters as well as `prevPage`/`prevOffset` representing the page/offset that was used before.

Note that the following is just an example for illustration. Stringified JSON objects in JavaScript should be encoded view `encodeURI()` before being used as query parameter.

[source]
----
GET /cats?page=1&size=3&sort=id,desc&prevPage=0&lowest={id:10}&highest={id:8}
{
    content: [
        { id: 7, name: 'Kitty', age: 1 },
        { id: 6, name: 'Bob', age: 8 },
        { id: 5, name: 'Frank', age: 14 }
    ]
}
----

This will make use of keyset pagination as can be seen by looking at the generated JPQL or SQL query.

Note that the client should _drop_ or _forget_ the `lowest`, `highest` and `prevPage`/`prevOffset` values when

* the page size changes and it is expected to show data not connected to the last page
* the sorting changes
* the filtering changes

For a full AngularJS example see the following https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-webmvc/src/main/resources/static/app.js[example project].

==== Entity view deserialization

The Spring Data WebMvc integration depends on the <<jackson-integration,Jackson integration>> and automatically provides support for deserializing entity views.
Currently, there is no support for constructor injection into entity views, so entity view attributes that should be deserializable should have a setter.

[source,java]
----
@EntityView(Cat.class)
@UpdatableEntityView
public interface CatUpdateView {

    @IdMapping
    Long getId();
    String getName();
    void setName(String name);
}

public interface CatViewRepository extends Repository<Cat, Long> {

    public CatUpdateView save(CatUpdateView catCreateView);
}
----

A controller can then deserialize entity views of request bodies by simply using it as `@RequestBody` annotated parameter like this:

[source,java]
----
@RestController
public class MyCatController {

    @Autowired
    private CatViewRepository catViewRepository;

    @RequestMapping(path = "/cats", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> updateCat(@RequestBody CatUpdateView catView) {
        catViewRepository.save(catView);
        return ResponseEntity.ok(catView.getId().toString());
    }
}
----

In the example above, the entity view id will be sourced from the request body. Alternatively, it is also possible to
retrieve the id from a path variable like this:

[source,java]
----
@RestController
public class MyCatController {

    @Autowired
    private CatViewRepository catViewRepository;

    @RequestMapping(path = "/cats/{id}", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> updateCat(@EntityViewId("id") @RequestBody CatUpdateView catView) {
        catViewRepository.save(catView);
        return ResponseEntity.ok(catView.getId().toString());
    }
}
----

=== Spring Data WebFlux integration

The Spring Data WebFlux integration provides the same features as the Spring Data WebMvc integration. In addition it also supports using `Mono` and `Flux` types.

[[spring-data-webmflux-setup]]
==== Setup

To setup the project for Spring Data WebFlux you have to add the following additional dependency.

[source,xml]
----
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-integration-spring-data-webflux</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
----

==== Usage

A controller can be written like for Spring Data WebMvc:

[source,java]
----
@RestController
public class MyCatController {

    @Autowired
    private KeysetAwareCatViewRepository simpleCatViewRepository;

    @RequestMapping(path = "/cats", method = RequestMethod.GET)
    public Page<SimpleCatView> getCats(@KeysetConfig(Cat.class) KeysetPageable pageable) {
        return simpleCatViewRepository.findAll(pageable);
    }
}
----

It can also use `Mono` or `Flux` types, but note that Spring Data JPA repositories don't support reactive access.

[source,java]
----
@Controller
public class MyCatController {

    @Autowired
    private KeysetAwareCatViewRepository simpleCatViewRepository;

    @Bean
    public RouterFunction<ServerResponse> createRouterFunctions(CatRestController controller) {
        return RouterFunctions.route(RequestPredicates.GET("/cats"), this::getCats);
    }

    public Flux<SimpleCatView> getCats() {
        return Flux.fromIterable(simpleCatViewRepository.findAll().getContent());
    }
}
----
